// Auto-generated by scrape.py — do not edit manually
// Last updated: 2026-03-23 19:44 UTC
const LCQ_DATA = [
  {
    "date": "2026-03-23",
    "format": "vintage",
    "event": "Vintage Last Chance 2026-03-23",
    "url": "https://www.mtggoldfish.com/tournament/62587",
    "players": 32,
    "decklists": [
      {
        "player": "Miharu_Fuyumiya",
        "deck": "Lurrus PO",
        "place": 1,
        "deck_url": "https://www.mtggoldfish.com/deck/7697768"
      },
      {
        "player": "scalo94",
        "deck": "Lurrus PO",
        "place": 2,
        "deck_url": "https://www.mtggoldfish.com/deck/7697754"
      },
      {
        "player": "IamActuallyLvL1",
        "deck": "Sphere Shops",
        "place": 3,
        "deck_url": "https://www.mtggoldfish.com/deck/7697762"
      },
      {
        "player": "Anonymous",
        "deck": "Sphere Shops",
        "place": 4,
        "deck_url": "https://www.mtggoldfish.com/deck/7697764"
      },
      {
        "player": "AFX",
        "deck": "Raker Shops",
        "place": 5,
        "deck_url": "https://www.mtggoldfish.com/deck/7697758"
      },
      {
        "player": "NathanOfTheGiltLeaf",
        "deck": "Esper Lurrus Control",
        "place": 6,
        "deck_url": "https://www.mtggoldfish.com/deck/7697772"
      },
      {
        "player": "_Shatun_",
        "deck": "Sphere Shops",
        "place": 7,
        "deck_url": "https://www.mtggoldfish.com/deck/7697756"
      },
      {
        "player": "4FunNoWin",
        "deck": "Lurrus PO",
        "place": 8,
        "deck_url": "https://www.mtggoldfish.com/deck/7697776"
      },
      {
        "player": "Tsubasa_Cat",
        "deck": "Dimir Lurrus Control",
        "place": 9,
        "deck_url": "https://www.mtggoldfish.com/deck/7697765"
      },
      {
        "player": "oskiyaa",
        "deck": "Dredge",
        "place": 10,
        "deck_url": "https://www.mtggoldfish.com/deck/7697759"
      },
      {
        "player": "crK",
        "deck": "Sphere Shops",
        "place": 11,
        "deck_url": "https://www.mtggoldfish.com/deck/7697755"
      },
      {
        "player": "HugoVenda",
        "deck": "Mono-White Initiative",
        "place": 12,
        "deck_url": "https://www.mtggoldfish.com/deck/7697751"
      },
      {
        "player": "duke12",
        "deck": "Lurrus PO",
        "place": 13,
        "deck_url": "https://www.mtggoldfish.com/deck/7697746"
      },
      {
        "player": "blub_blub",
        "deck": "Lurrus Breach",
        "place": 14,
        "deck_url": "https://www.mtggoldfish.com/deck/7697777"
      },
      {
        "player": "magiclaszlo",
        "deck": "Sphere Shops",
        "place": 15,
        "deck_url": "https://www.mtggoldfish.com/deck/7697747"
      },
      {
        "player": "sebastianpozzo",
        "deck": "Dredge",
        "place": 16,
        "deck_url": "https://www.mtggoldfish.com/deck/7697748"
      },
      {
        "player": "_Batutinha_",
        "deck": "Esper Lurrus Control",
        "place": 17,
        "deck_url": "https://www.mtggoldfish.com/deck/7697749"
      },
      {
        "player": "MJ_23",
        "deck": "Mono-White Initiative",
        "place": 18,
        "deck_url": "https://www.mtggoldfish.com/deck/7697753"
      },
      {
        "player": "xfile",
        "deck": "Lurrus PO",
        "place": 19,
        "deck_url": "https://www.mtggoldfish.com/deck/7697767"
      },
      {
        "player": "inspiratiekever",
        "deck": "Lurrus PO",
        "place": 20,
        "deck_url": "https://www.mtggoldfish.com/deck/7697775"
      },
      {
        "player": "chanel-santini",
        "deck": "Doomsday",
        "place": 21,
        "deck_url": "https://www.mtggoldfish.com/deck/7697773"
      },
      {
        "player": "boytriton",
        "deck": "Lurrus Breach",
        "place": 22,
        "deck_url": "https://www.mtggoldfish.com/deck/7697770"
      },
      {
        "player": "thestudygroup",
        "deck": "Esper Lurrus Control",
        "place": 23,
        "deck_url": "https://www.mtggoldfish.com/deck/7697760"
      },
      {
        "player": "mortr3d",
        "deck": "Raker Shops",
        "place": 24,
        "deck_url": "https://www.mtggoldfish.com/deck/7697750"
      },
      {
        "player": "Frejat",
        "deck": "Esper Lurrus Control",
        "place": 25,
        "deck_url": "https://www.mtggoldfish.com/deck/7697761"
      },
      {
        "player": "LucasG1ggs",
        "deck": "Sphere Shops",
        "place": 26,
        "deck_url": "https://www.mtggoldfish.com/deck/7697752"
      },
      {
        "player": "ecobaronen",
        "deck": "Dimir Lurrus Control",
        "place": 27,
        "deck_url": "https://www.mtggoldfish.com/deck/7697757"
      },
      {
        "player": "416FrowningTable",
        "deck": "Lurrus Breach",
        "place": 28,
        "deck_url": "https://www.mtggoldfish.com/deck/7697766"
      },
      {
        "player": "Milkshake_",
        "deck": "Sphere Shops",
        "place": 29,
        "deck_url": "https://www.mtggoldfish.com/deck/7697774"
      },
      {
        "player": "Univerce",
        "deck": "Doomsday",
        "place": 30,
        "deck_url": "https://www.mtggoldfish.com/deck/7697771"
      },
      {
        "player": "blackdecks99",
        "deck": "Dredge",
        "place": 31,
        "deck_url": "https://www.mtggoldfish.com/deck/7697763"
      },
      {
        "player": "-Nausea-",
        "deck": "Jewel Shops",
        "place": 32,
        "deck_url": "https://www.mtggoldfish.com/deck/7697769"
      }
    ]
  },
  {
    "date": "2026-03-23",
    "format": "standard",
    "event": "Standard Last Chance 2026-03-23 (1)",
    "url": "https://www.mtggoldfish.com/tournament/62585",
    "players": 32,
    "decklists": [
      {
        "player": "kanister",
        "deck": "Izzet Lessons",
        "place": 1,
        "deck_url": "https://www.mtggoldfish.com/deck/7697499"
      },
      {
        "player": "Salvatto",
        "deck": "Mono-Green Landfall",
        "place": 2,
        "deck_url": "https://www.mtggoldfish.com/deck/7697493"
      },
      {
        "player": "SanPop",
        "deck": "Izzet Prowess",
        "place": 3,
        "deck_url": "https://www.mtggoldfish.com/deck/7697504"
      },
      {
        "player": "RCMerriam",
        "deck": "Izzet Prowess",
        "place": 4,
        "deck_url": "https://www.mtggoldfish.com/deck/7697494"
      },
      {
        "player": "willjetz1323",
        "deck": "Mono-Green Landfall",
        "place": 5,
        "deck_url": "https://www.mtggoldfish.com/deck/7697495"
      },
      {
        "player": "RespectTheCat",
        "deck": "5c Elementals",
        "place": 6,
        "deck_url": "https://www.mtggoldfish.com/deck/7697510"
      },
      {
        "player": "Valimoth",
        "deck": "Izzet Spellementals",
        "place": 7,
        "deck_url": "https://www.mtggoldfish.com/deck/7697514"
      },
      {
        "player": "MKC",
        "deck": "Mono-Green Landfall",
        "place": 8,
        "deck_url": "https://www.mtggoldfish.com/deck/7697491"
      },
      {
        "player": "surgetemelo",
        "deck": "Dimir Excruciator",
        "place": 9,
        "deck_url": "https://www.mtggoldfish.com/deck/7697521"
      },
      {
        "player": "_Tia93_",
        "deck": "Izzet Lessons",
        "place": 10,
        "deck_url": "https://www.mtggoldfish.com/deck/7697500"
      },
      {
        "player": "ashame",
        "deck": "Izzet Prowess",
        "place": 11,
        "deck_url": "https://www.mtggoldfish.com/deck/7697509"
      },
      {
        "player": "Azja",
        "deck": "Izzet Prowess",
        "place": 12,
        "deck_url": "https://www.mtggoldfish.com/deck/7697508"
      },
      {
        "player": "Ale_Mtg",
        "deck": "Bant Ouroboroid",
        "place": 13,
        "deck_url": "https://www.mtggoldfish.com/deck/7697506"
      },
      {
        "player": "NJ5030",
        "deck": "Izzet Prowess",
        "place": 14,
        "deck_url": "https://www.mtggoldfish.com/deck/7697516"
      },
      {
        "player": "Xenowan",
        "deck": "4c Ouroboroid",
        "place": 15,
        "deck_url": "https://www.mtggoldfish.com/deck/7697503"
      },
      {
        "player": "elBB",
        "deck": "Izzet Prowess",
        "place": 16,
        "deck_url": "https://www.mtggoldfish.com/deck/7697515"
      },
      {
        "player": "CrazyMorango",
        "deck": "Izzet Lessons",
        "place": 17,
        "deck_url": "https://www.mtggoldfish.com/deck/7697513"
      },
      {
        "player": "terlollo04",
        "deck": "Izzet Prowess",
        "place": 18,
        "deck_url": "https://www.mtggoldfish.com/deck/7697502"
      },
      {
        "player": "Thief_Of_Crowns",
        "deck": "BG",
        "place": 19,
        "deck_url": "https://www.mtggoldfish.com/deck/7697517"
      },
      {
        "player": "Terminus0",
        "deck": "Izzet Lessons",
        "place": 20,
        "deck_url": "https://www.mtggoldfish.com/deck/7697501"
      },
      {
        "player": "Mldyss",
        "deck": "Izzet Spellementals",
        "place": 21,
        "deck_url": "https://www.mtggoldfish.com/deck/7697511"
      },
      {
        "player": "sebastianpozzo",
        "deck": "Bant Ouroboroid",
        "place": 22,
        "deck_url": "https://www.mtggoldfish.com/deck/7697490"
      },
      {
        "player": "Kritik",
        "deck": "4c Control",
        "place": 23,
        "deck_url": "https://www.mtggoldfish.com/deck/7697507"
      },
      {
        "player": "BERNASTORRES",
        "deck": "Izzet Spellementals",
        "place": 24,
        "deck_url": "https://www.mtggoldfish.com/deck/7697496"
      },
      {
        "player": "MultiformatSuperstar",
        "deck": "Izzet Spellementals",
        "place": 25,
        "deck_url": "https://www.mtggoldfish.com/deck/7697505"
      },
      {
        "player": "LucasG1ggs",
        "deck": "Mono-Green Landfall",
        "place": 26,
        "deck_url": "https://www.mtggoldfish.com/deck/7697492"
      },
      {
        "player": "MacIsaac",
        "deck": "Temur Prowess",
        "place": 27,
        "deck_url": "https://www.mtggoldfish.com/deck/7697519"
      },
      {
        "player": "SpockVidaLoka",
        "deck": "Bant Ouroboroid",
        "place": 28,
        "deck_url": "https://www.mtggoldfish.com/deck/7697512"
      },
      {
        "player": "makaaaa",
        "deck": "Izzet Prowess",
        "place": 29,
        "deck_url": "https://www.mtggoldfish.com/deck/7697518"
      },
      {
        "player": "Venom1",
        "deck": "Mono-Green Landfall",
        "place": 30,
        "deck_url": "https://www.mtggoldfish.com/deck/7697497"
      },
      {
        "player": "groot02",
        "deck": "Izzet Lessons",
        "place": 31,
        "deck_url": "https://www.mtggoldfish.com/deck/7697520"
      },
      {
        "player": "wolf2222",
        "deck": "Izzet Spellementals",
        "place": 32,
        "deck_url": "https://www.mtggoldfish.com/deck/7697498"
      }
    ]
  },
  {
    "date": "2026-03-23",
    "format": "standard",
    "event": "Standard Last Chance 2026-03-23 (1)",
    "url": "https://www.mtggoldfish.com/tournament/62577",
    "players": 32,
    "decklists": [
      {
        "player": "rastaf",
        "deck": "Mono-Green Landfall",
        "place": 1,
        "deck_url": "https://www.mtggoldfish.com/deck/7697037"
      },
      {
        "player": "Capriccioso",
        "deck": "Azorius Momo",
        "place": 2,
        "deck_url": "https://www.mtggoldfish.com/deck/7697041"
      },
      {
        "player": "eggybenny",
        "deck": "Izzet Prowess",
        "place": 3,
        "deck_url": "https://www.mtggoldfish.com/deck/7697052"
      },
      {
        "player": "_Babbuja_",
        "deck": "Dimir Excruciator",
        "place": 4,
        "deck_url": "https://www.mtggoldfish.com/deck/7697066"
      },
      {
        "player": "LucasG1ggs",
        "deck": "Mono-Green Landfall",
        "place": 5,
        "deck_url": "https://www.mtggoldfish.com/deck/7697043"
      },
      {
        "player": "GTX120",
        "deck": "Mono-White Momo",
        "place": 6,
        "deck_url": "https://www.mtggoldfish.com/deck/7697049"
      },
      {
        "player": "Chichichi",
        "deck": "Izzet Spellementals",
        "place": 7,
        "deck_url": "https://www.mtggoldfish.com/deck/7697055"
      },
      {
        "player": "ashame",
        "deck": "Izzet Prowess",
        "place": 8,
        "deck_url": "https://www.mtggoldfish.com/deck/7697054"
      },
      {
        "player": "indianpancake",
        "deck": "Mono-Green Landfall",
        "place": 9,
        "deck_url": "https://www.mtggoldfish.com/deck/7697047"
      },
      {
        "player": "NJ5030",
        "deck": "Izzet Prowess",
        "place": 10,
        "deck_url": "https://www.mtggoldfish.com/deck/7697062"
      },
      {
        "player": "VictorEsquici",
        "deck": "Izzet Spellementals",
        "place": 11,
        "deck_url": "https://www.mtggoldfish.com/deck/7697061"
      },
      {
        "player": "Salvatto",
        "deck": "Bant Ouroboroid",
        "place": 12,
        "deck_url": "https://www.mtggoldfish.com/deck/7697045"
      },
      {
        "player": "CrazyMorango",
        "deck": "Izzet Lessons",
        "place": 13,
        "deck_url": "https://www.mtggoldfish.com/deck/7697057"
      },
      {
        "player": "Valimoth",
        "deck": "Izzet Spellementals",
        "place": 14,
        "deck_url": "https://www.mtggoldfish.com/deck/7697058"
      },
      {
        "player": "Skeptic2304",
        "deck": "Mono-Green Landfall",
        "place": 15,
        "deck_url": "https://www.mtggoldfish.com/deck/7697051"
      },
      {
        "player": "duke12",
        "deck": "4c Harmonizer Combo",
        "place": 16,
        "deck_url": "https://www.mtggoldfish.com/deck/7697035"
      },
      {
        "player": "Univerce",
        "deck": "4c Ouroboroid",
        "place": 17,
        "deck_url": "https://www.mtggoldfish.com/deck/7697056"
      },
      {
        "player": "Misplacedginger",
        "deck": "Izzet Lessons",
        "place": 18,
        "deck_url": "https://www.mtggoldfish.com/deck/7697042"
      },
      {
        "player": "ShadowTitan1",
        "deck": "Bant Ouroboroid",
        "place": 19,
        "deck_url": "https://www.mtggoldfish.com/deck/7697048"
      },
      {
        "player": "Merriman",
        "deck": "4c Ouroboroid",
        "place": 20,
        "deck_url": "https://www.mtggoldfish.com/deck/7697064"
      },
      {
        "player": "wolf2222",
        "deck": "Izzet Spellementals",
        "place": 21,
        "deck_url": "https://www.mtggoldfish.com/deck/7697046"
      },
      {
        "player": "Bruskk",
        "deck": "Izzet Lessons",
        "place": 22,
        "deck_url": "https://www.mtggoldfish.com/deck/7697060"
      },
      {
        "player": "Milkshake_",
        "deck": "Izzet Prowess",
        "place": 23,
        "deck_url": "https://www.mtggoldfish.com/deck/7697065"
      },
      {
        "player": "Azja",
        "deck": "Izzet Prowess",
        "place": 24,
        "deck_url": "https://www.mtggoldfish.com/deck/7697053"
      },
      {
        "player": "L1X0",
        "deck": "Mono-Green Landfall",
        "place": 25,
        "deck_url": "https://www.mtggoldfish.com/deck/7697039"
      },
      {
        "player": "Shamplade",
        "deck": "Mono-Green Landfall",
        "place": 26,
        "deck_url": "https://www.mtggoldfish.com/deck/7697059"
      },
      {
        "player": "xfile",
        "deck": "Izzet Lessons",
        "place": 27,
        "deck_url": "https://www.mtggoldfish.com/deck/7697050"
      },
      {
        "player": "Nocturne_",
        "deck": "Orzhov Midrange",
        "place": 28,
        "deck_url": "https://www.mtggoldfish.com/deck/7697044"
      },
      {
        "player": "levunga21",
        "deck": "Dimir Midrange",
        "place": 29,
        "deck_url": "https://www.mtggoldfish.com/deck/7697040"
      },
      {
        "player": "sebastianpozzo",
        "deck": "Bant Ouroboroid",
        "place": 30,
        "deck_url": "https://www.mtggoldfish.com/deck/7697038"
      },
      {
        "player": "digdude13",
        "deck": "Boros Momo",
        "place": 31,
        "deck_url": "https://www.mtggoldfish.com/deck/7697036"
      },
      {
        "player": "PedraStone",
        "deck": "Izzet Lessons",
        "place": 32,
        "deck_url": "https://www.mtggoldfish.com/deck/7697063"
      }
    ]
  },
  {
    "date": "2026-03-23",
    "format": "legacy",
    "event": "Legacy Last Chance 2026-03-23",
    "url": "https://www.mtggoldfish.com/tournament/62564",
    "players": 32,
    "decklists": [
      {
        "player": "Thalai",
        "deck": "Colorless",
        "place": 1,
        "deck_url": "https://www.mtggoldfish.com/deck/7695827"
      },
      {
        "player": "snoopy-magic",
        "deck": "Sneak and Show",
        "place": 2,
        "deck_url": "https://www.mtggoldfish.com/deck/7695838"
      },
      {
        "player": "Otazz",
        "deck": "Sultai Aluren",
        "place": 3,
        "deck_url": "https://www.mtggoldfish.com/deck/7695839"
      },
      {
        "player": "_INF_",
        "deck": "Dimir Tempo",
        "place": 4,
        "deck_url": "https://www.mtggoldfish.com/deck/7695845"
      },
      {
        "player": "choutin",
        "deck": "Oops! All Spells",
        "place": 5,
        "deck_url": "https://www.mtggoldfish.com/deck/7695856"
      },
      {
        "player": "Comrade1312",
        "deck": "Oops! All Spells",
        "place": 6,
        "deck_url": "https://www.mtggoldfish.com/deck/7695841"
      },
      {
        "player": "TheGrimLavamancer",
        "deck": "Sneak and Show",
        "place": 7,
        "deck_url": "https://www.mtggoldfish.com/deck/7695848"
      },
      {
        "player": "KurumimBagoRosa",
        "deck": "Colorless",
        "place": 8,
        "deck_url": "https://www.mtggoldfish.com/deck/7695858"
      },
      {
        "player": "kanican",
        "deck": "UBR",
        "place": 9,
        "deck_url": "https://www.mtggoldfish.com/deck/7695834"
      },
      {
        "player": "Vlalutscher",
        "deck": "The EPIC Storm",
        "place": 10,
        "deck_url": "https://www.mtggoldfish.com/deck/7695849"
      },
      {
        "player": "Xenowan",
        "deck": "Colorless",
        "place": 11,
        "deck_url": "https://www.mtggoldfish.com/deck/7695842"
      },
      {
        "player": "SlayItWithRoses",
        "deck": "Red Stompy",
        "place": 12,
        "deck_url": "https://www.mtggoldfish.com/deck/7695833"
      },
      {
        "player": "boytriton",
        "deck": "Colorless",
        "place": 13,
        "deck_url": "https://www.mtggoldfish.com/deck/7695850"
      },
      {
        "player": "JohnDoe397",
        "deck": "Death and Taxes (Yorion) - Orzhov",
        "place": 14,
        "deck_url": "https://www.mtggoldfish.com/deck/7695852"
      },
      {
        "player": "ReformedPaolo",
        "deck": "Dimir Tempo",
        "place": 15,
        "deck_url": "https://www.mtggoldfish.com/deck/7695843"
      },
      {
        "player": "manohito",
        "deck": "Oops! All Spells",
        "place": 16,
        "deck_url": "https://www.mtggoldfish.com/deck/7695851"
      },
      {
        "player": "RedArmada",
        "deck": "Dimir Reanimator",
        "place": 17,
        "deck_url": "https://www.mtggoldfish.com/deck/7695829"
      },
      {
        "player": "_Batutinha_",
        "deck": "Colorless",
        "place": 18,
        "deck_url": "https://www.mtggoldfish.com/deck/7695828"
      },
      {
        "player": "Rhysiner",
        "deck": "BG",
        "place": 19,
        "deck_url": "https://www.mtggoldfish.com/deck/7695835"
      },
      {
        "player": "discoverN",
        "deck": "Dimir Tempo",
        "place": 20,
        "deck_url": "https://www.mtggoldfish.com/deck/7695831"
      },
      {
        "player": "pepeteam",
        "deck": "Dimir Tempo",
        "place": 21,
        "deck_url": "https://www.mtggoldfish.com/deck/7695840"
      },
      {
        "player": "NathanLipetz",
        "deck": "Oops! All Spells",
        "place": 22,
        "deck_url": "https://www.mtggoldfish.com/deck/7695844"
      },
      {
        "player": "Munchlax446",
        "deck": "Dimir Tempo",
        "place": 23,
        "deck_url": "https://www.mtggoldfish.com/deck/7695854"
      },
      {
        "player": "JV_7777",
        "deck": "Dimir Tempo",
        "place": 24,
        "deck_url": "https://www.mtggoldfish.com/deck/7695836"
      },
      {
        "player": "GigaChadSigmaMale",
        "deck": "Dimir Tempo",
        "place": 25,
        "deck_url": "https://www.mtggoldfish.com/deck/7695855"
      },
      {
        "player": "zhinonono",
        "deck": "Lands",
        "place": 26,
        "deck_url": "https://www.mtggoldfish.com/deck/7695837"
      },
      {
        "player": "clan",
        "deck": "Doomsday",
        "place": 27,
        "deck_url": "https://www.mtggoldfish.com/deck/7695847"
      },
      {
        "player": "Ark4n",
        "deck": "Esper Control",
        "place": 28,
        "deck_url": "https://www.mtggoldfish.com/deck/7695832"
      },
      {
        "player": "HugoVenda",
        "deck": "Dimir Tempo",
        "place": 29,
        "deck_url": "https://www.mtggoldfish.com/deck/7695830"
      },
      {
        "player": "VenusCHN",
        "deck": "Sneak and Show",
        "place": 30,
        "deck_url": "https://www.mtggoldfish.com/deck/7695857"
      },
      {
        "player": "Roodslay",
        "deck": "UBG",
        "place": 31,
        "deck_url": "https://www.mtggoldfish.com/deck/7695846"
      },
      {
        "player": "Univerce",
        "deck": "Lands",
        "place": 32,
        "deck_url": "https://www.mtggoldfish.com/deck/7695853"
      }
    ]
  },
  {
    "date": "2026-03-23",
    "format": "modern",
    "event": "Modern Last Chance 2026-03-23",
    "url": "https://www.mtggoldfish.com/tournament/62560",
    "players": 32,
    "decklists": [
      {
        "player": "kanister",
        "deck": "Amulet Titan",
        "place": 1,
        "deck_url": "https://www.mtggoldfish.com/deck/7695668"
      },
      {
        "player": "badgods",
        "deck": "Belcher",
        "place": 2,
        "deck_url": "https://www.mtggoldfish.com/deck/7695683"
      },
      {
        "player": "surgetemelo",
        "deck": "Boros Energy",
        "place": 3,
        "deck_url": "https://www.mtggoldfish.com/deck/7695692"
      },
      {
        "player": "pizzangry",
        "deck": "Ruby Storm",
        "place": 4,
        "deck_url": "https://www.mtggoldfish.com/deck/7695687"
      },
      {
        "player": "sioutis_kk",
        "deck": "Affinity",
        "place": 5,
        "deck_url": "https://www.mtggoldfish.com/deck/7695693"
      },
      {
        "player": "WeareVenom",
        "deck": "Amulet Titan",
        "place": 6,
        "deck_url": "https://www.mtggoldfish.com/deck/7695680"
      },
      {
        "player": "azax",
        "deck": "Ruby Storm",
        "place": 7,
        "deck_url": "https://www.mtggoldfish.com/deck/7695674"
      },
      {
        "player": "JMAK2000",
        "deck": "Mono-Green Tron",
        "place": 8,
        "deck_url": "https://www.mtggoldfish.com/deck/7695671"
      },
      {
        "player": "scipios",
        "deck": "Jeskai Control",
        "place": 9,
        "deck_url": "https://www.mtggoldfish.com/deck/7695679"
      },
      {
        "player": "Ebnus",
        "deck": "Izzet Prowess",
        "place": 10,
        "deck_url": "https://www.mtggoldfish.com/deck/7695672"
      },
      {
        "player": "MTGHolic",
        "deck": "Jeskai Blink",
        "place": 11,
        "deck_url": "https://www.mtggoldfish.com/deck/7695686"
      },
      {
        "player": "klien7",
        "deck": "Jeskai Blink",
        "place": 12,
        "deck_url": "https://www.mtggoldfish.com/deck/7695682"
      },
      {
        "player": "Capitano_CL",
        "deck": "Ruby Storm",
        "place": 13,
        "deck_url": "https://www.mtggoldfish.com/deck/7695663"
      },
      {
        "player": "HugoVenda",
        "deck": "Jeskai Control",
        "place": 14,
        "deck_url": "https://www.mtggoldfish.com/deck/7695664"
      },
      {
        "player": "TomCairns",
        "deck": "Dimir Reanimator",
        "place": 15,
        "deck_url": "https://www.mtggoldfish.com/deck/7695691"
      },
      {
        "player": "Cachorrowo",
        "deck": "Ruby Storm",
        "place": 16,
        "deck_url": "https://www.mtggoldfish.com/deck/7695684"
      },
      {
        "player": "KadettiKersantti",
        "deck": "Grixis Reanimator",
        "place": 17,
        "deck_url": "https://www.mtggoldfish.com/deck/7695690"
      },
      {
        "player": "brandi96",
        "deck": "Boros Energy",
        "place": 18,
        "deck_url": "https://www.mtggoldfish.com/deck/7695670"
      },
      {
        "player": "Omegauo",
        "deck": "Esper GenericBlink",
        "place": 19,
        "deck_url": "https://www.mtggoldfish.com/deck/7695661"
      },
      {
        "player": "toondoslav",
        "deck": "Esper GenericBlink",
        "place": 20,
        "deck_url": "https://www.mtggoldfish.com/deck/7695669"
      },
      {
        "player": "GigaChadSigmaMale",
        "deck": "Goryo&#39;s Vengeance",
        "place": 21,
        "deck_url": "https://www.mtggoldfish.com/deck/7695688"
      },
      {
        "player": "pepeteam",
        "deck": "Dimir Midrange",
        "place": 22,
        "deck_url": "https://www.mtggoldfish.com/deck/7695675"
      },
      {
        "player": "Univerce",
        "deck": "Affinity",
        "place": 23,
        "deck_url": "https://www.mtggoldfish.com/deck/7695685"
      },
      {
        "player": "chengyiw",
        "deck": "Goryo&#39;s Vengeance",
        "place": 24,
        "deck_url": "https://www.mtggoldfish.com/deck/7695678"
      },
      {
        "player": "felider",
        "deck": "Jeskai Blink",
        "place": 25,
        "deck_url": "https://www.mtggoldfish.com/deck/7695677"
      },
      {
        "player": "FakeShaver",
        "deck": "Belcher",
        "place": 26,
        "deck_url": "https://www.mtggoldfish.com/deck/7695662"
      },
      {
        "player": "Athenani",
        "deck": "Boros Energy",
        "place": 27,
        "deck_url": "https://www.mtggoldfish.com/deck/7695689"
      },
      {
        "player": "JPA93",
        "deck": "Neobrand",
        "place": 28,
        "deck_url": "https://www.mtggoldfish.com/deck/7695667"
      },
      {
        "player": "Terminus0",
        "deck": "Esper GenericBlink",
        "place": 29,
        "deck_url": "https://www.mtggoldfish.com/deck/7695673"
      },
      {
        "player": "Gerschi",
        "deck": "Living End",
        "place": 30,
        "deck_url": "https://www.mtggoldfish.com/deck/7695665"
      },
      {
        "player": "Venom1",
        "deck": "Jeskai Blink",
        "place": 31,
        "deck_url": "https://www.mtggoldfish.com/deck/7695666"
      },
      {
        "player": "bless_von",
        "deck": "Boros Energy",
        "place": 32,
        "deck_url": "https://www.mtggoldfish.com/deck/7695676"
      }
    ]
  },
  {
    "date": "2026-03-22",
    "format": "modern",
    "event": "Modern Last Chance 2026-03-22 (1)",
    "url": "https://www.mtggoldfish.com/tournament/62588",
    "players": 32,
    "decklists": [
      {
        "player": "ETBJezus",
        "deck": "Dimir Midrange",
        "place": 1,
        "deck_url": "https://www.mtggoldfish.com/deck/7697826"
      },
      {
        "player": "xDingusKhan",
        "deck": "Ruby Storm",
        "place": 2,
        "deck_url": "https://www.mtggoldfish.com/deck/7697814"
      },
      {
        "player": "Laplasjan",
        "deck": "Jeskai Blink",
        "place": 3,
        "deck_url": "https://www.mtggoldfish.com/deck/7697809"
      },
      {
        "player": "Pmizz",
        "deck": "Jeskai Blink",
        "place": 4,
        "deck_url": "https://www.mtggoldfish.com/deck/7697811"
      },
      {
        "player": "eclipse4343",
        "deck": "Azorius Control",
        "place": 5,
        "deck_url": "https://www.mtggoldfish.com/deck/7697818"
      },
      {
        "player": "O_danielakos",
        "deck": "Temur Prowess",
        "place": 6,
        "deck_url": "https://www.mtggoldfish.com/deck/7697803"
      },
      {
        "player": "Crovax90",
        "deck": "Jeskai Blink",
        "place": 7,
        "deck_url": "https://www.mtggoldfish.com/deck/7697813"
      },
      {
        "player": "RUBAO_oDonoDoMundo",
        "deck": "Ruby Storm",
        "place": 8,
        "deck_url": "https://www.mtggoldfish.com/deck/7697827"
      },
      {
        "player": "Yarfangel",
        "deck": "Jeskai Blink",
        "place": 9,
        "deck_url": "https://www.mtggoldfish.com/deck/7697828"
      },
      {
        "player": "Moorehardcore",
        "deck": "Yawgmoth",
        "place": 10,
        "deck_url": "https://www.mtggoldfish.com/deck/7697825"
      },
      {
        "player": "Univerce",
        "deck": "Affinity",
        "place": 11,
        "deck_url": "https://www.mtggoldfish.com/deck/7697822"
      },
      {
        "player": "sioutis_kk",
        "deck": "Affinity",
        "place": 12,
        "deck_url": "https://www.mtggoldfish.com/deck/7697831"
      },
      {
        "player": "Xerk",
        "deck": "Yawgmoth",
        "place": 13,
        "deck_url": "https://www.mtggoldfish.com/deck/7697806"
      },
      {
        "player": "cigarettesaftershrek",
        "deck": "Affinity",
        "place": 14,
        "deck_url": "https://www.mtggoldfish.com/deck/7697824"
      },
      {
        "player": "sokos13",
        "deck": "Jeskai Blink",
        "place": 15,
        "deck_url": "https://www.mtggoldfish.com/deck/7697800"
      },
      {
        "player": "toondoslav",
        "deck": "Esper GenericBlink",
        "place": 16,
        "deck_url": "https://www.mtggoldfish.com/deck/7697810"
      },
      {
        "player": "Nilsfit",
        "deck": "Jeskai Control",
        "place": 17,
        "deck_url": "https://www.mtggoldfish.com/deck/7697815"
      },
      {
        "player": "Napoleon_I",
        "deck": "Naya Energy",
        "place": 18,
        "deck_url": "https://www.mtggoldfish.com/deck/7697819"
      },
      {
        "player": "Cazuza",
        "deck": "Jeskai Blink",
        "place": 19,
        "deck_url": "https://www.mtggoldfish.com/deck/7697820"
      },
      {
        "player": "mendyourheart",
        "deck": "Domain Zoo",
        "place": 20,
        "deck_url": "https://www.mtggoldfish.com/deck/7697829"
      },
      {
        "player": "DemonicTutors",
        "deck": "Yawgmoth",
        "place": 21,
        "deck_url": "https://www.mtggoldfish.com/deck/7697821"
      },
      {
        "player": "Foxantes",
        "deck": "Boros Energy",
        "place": 22,
        "deck_url": "https://www.mtggoldfish.com/deck/7697812"
      },
      {
        "player": "Venom1",
        "deck": "Jeskai Blink",
        "place": 23,
        "deck_url": "https://www.mtggoldfish.com/deck/7697807"
      },
      {
        "player": "pottinkx",
        "deck": "Boros Energy",
        "place": 24,
        "deck_url": "https://www.mtggoldfish.com/deck/7697830"
      },
      {
        "player": "applefox",
        "deck": "Living End",
        "place": 25,
        "deck_url": "https://www.mtggoldfish.com/deck/7697823"
      },
      {
        "player": "MultiformatSuperstar",
        "deck": "Neobrand",
        "place": 26,
        "deck_url": "https://www.mtggoldfish.com/deck/7697817"
      },
      {
        "player": "J4K3ST3R02",
        "deck": "Affinity",
        "place": 27,
        "deck_url": "https://www.mtggoldfish.com/deck/7697808"
      },
      {
        "player": "LucasG1ggs",
        "deck": "Boros Energy",
        "place": 28,
        "deck_url": "https://www.mtggoldfish.com/deck/7697802"
      },
      {
        "player": "Xenowan",
        "deck": "Neobrand",
        "place": 29,
        "deck_url": "https://www.mtggoldfish.com/deck/7697816"
      },
      {
        "player": "aspiringspike",
        "deck": "Dimir Midrange",
        "place": 30,
        "deck_url": "https://www.mtggoldfish.com/deck/7697804"
      },
      {
        "player": "tibalt_of_red_sub",
        "deck": "Dimir Mill",
        "place": 31,
        "deck_url": "https://www.mtggoldfish.com/deck/7697805"
      },
      {
        "player": "Misplacedginger",
        "deck": "Jeskai Blink",
        "place": 32,
        "deck_url": "https://www.mtggoldfish.com/deck/7697801"
      }
    ]
  }
];
