// Auto-generated by scrape.py — do not edit manually
// Last updated: 2026-03-23 23:10 UTC
const LCQ_DATA = [
  {
    "date": "2026-03-23",
    "format": "vintage",
    "event": "Vintage Last Chance 2026-03-23",
    "url": "https://www.mtggoldfish.com/tournament/62587",
    "players": 32,
    "decklists": [
      {
        "player": "Miharu_Fuyumiya",
        "deck": "Lurrus PO",
        "place": 1
      },
      {
        "player": "scalo94",
        "deck": "Lurrus PO",
        "place": 2
      },
      {
        "player": "IamActuallyLvL1",
        "deck": "Sphere Shops",
        "place": 3
      },
      {
        "player": "Anonymous",
        "deck": "Sphere Shops",
        "place": 4
      },
      {
        "player": "AFX",
        "deck": "Raker Shops",
        "place": 5
      },
      {
        "player": "NathanOfTheGiltLeaf",
        "deck": "Esper Lurrus Control",
        "place": 6
      },
      {
        "player": "_Shatun_",
        "deck": "Sphere Shops",
        "place": 7
      },
      {
        "player": "4FunNoWin",
        "deck": "Lurrus PO",
        "place": 8
      },
      {
        "player": "Tsubasa_Cat",
        "deck": "Dimir Lurrus Control",
        "place": 9
      },
      {
        "player": "oskiyaa",
        "deck": "Dredge",
        "place": 10
      },
      {
        "player": "crK",
        "deck": "Sphere Shops",
        "place": 11
      },
      {
        "player": "HugoVenda",
        "deck": "Mono-White Initiative",
        "place": 12
      },
      {
        "player": "duke12",
        "deck": "Lurrus PO",
        "place": 13
      },
      {
        "player": "blub_blub",
        "deck": "Lurrus Breach",
        "place": 14
      },
      {
        "player": "magiclaszlo",
        "deck": "Sphere Shops",
        "place": 15
      },
      {
        "player": "sebastianpozzo",
        "deck": "Dredge",
        "place": 16
      },
      {
        "player": "_Batutinha_",
        "deck": "Esper Lurrus Control",
        "place": 17
      },
      {
        "player": "MJ_23",
        "deck": "Mono-White Initiative",
        "place": 18
      },
      {
        "player": "xfile",
        "deck": "Lurrus PO",
        "place": 19
      },
      {
        "player": "inspiratiekever",
        "deck": "Lurrus PO",
        "place": 20
      },
      {
        "player": "chanel-santini",
        "deck": "Doomsday",
        "place": 21
      },
      {
        "player": "boytriton",
        "deck": "Lurrus Breach",
        "place": 22
      },
      {
        "player": "thestudygroup",
        "deck": "Esper Lurrus Control",
        "place": 23
      },
      {
        "player": "mortr3d",
        "deck": "Raker Shops",
        "place": 24
      },
      {
        "player": "Frejat",
        "deck": "Esper Lurrus Control",
        "place": 25
      },
      {
        "player": "LucasG1ggs",
        "deck": "Sphere Shops",
        "place": 26
      },
      {
        "player": "ecobaronen",
        "deck": "Dimir Lurrus Control",
        "place": 27
      },
      {
        "player": "416FrowningTable",
        "deck": "Lurrus Breach",
        "place": 28
      },
      {
        "player": "Milkshake_",
        "deck": "Sphere Shops",
        "place": 29
      },
      {
        "player": "Univerce",
        "deck": "Doomsday",
        "place": 30
      },
      {
        "player": "blackdecks99",
        "deck": "Dredge",
        "place": 31
      },
      {
        "player": "-Nausea-",
        "deck": "Jewel Shops",
        "place": 32
      }
    ]
  },
  {
    "date": "2026-03-23",
    "format": "standard",
    "event": "Standard Last Chance 2026-03-23 (1)",
    "url": "https://www.mtggoldfish.com/tournament/62585",
    "players": 32,
    "decklists": [
      {
        "player": "kanister",
        "deck": "Izzet Lessons",
        "place": 1
      },
      {
        "player": "Salvatto",
        "deck": "Mono-Green Landfall",
        "place": 2
      },
      {
        "player": "SanPop",
        "deck": "Izzet Prowess",
        "place": 3
      },
      {
        "player": "RCMerriam",
        "deck": "Izzet Prowess",
        "place": 4
      },
      {
        "player": "willjetz1323",
        "deck": "Mono-Green Landfall",
        "place": 5
      },
      {
        "player": "RespectTheCat",
        "deck": "5c Elementals",
        "place": 6
      },
      {
        "player": "Valimoth",
        "deck": "Izzet Spellementals",
        "place": 7
      },
      {
        "player": "MKC",
        "deck": "Mono-Green Landfall",
        "place": 8
      },
      {
        "player": "surgetemelo",
        "deck": "Dimir Excruciator",
        "place": 9
      },
      {
        "player": "_Tia93_",
        "deck": "Izzet Lessons",
        "place": 10
      },
      {
        "player": "ashame",
        "deck": "Izzet Prowess",
        "place": 11
      },
      {
        "player": "Azja",
        "deck": "Izzet Prowess",
        "place": 12
      },
      {
        "player": "Ale_Mtg",
        "deck": "Bant Ouroboroid",
        "place": 13
      },
      {
        "player": "NJ5030",
        "deck": "Izzet Prowess",
        "place": 14
      },
      {
        "player": "Xenowan",
        "deck": "4c Ouroboroid",
        "place": 15
      },
      {
        "player": "elBB",
        "deck": "Izzet Prowess",
        "place": 16
      },
      {
        "player": "CrazyMorango",
        "deck": "Izzet Lessons",
        "place": 17
      },
      {
        "player": "terlollo04",
        "deck": "Izzet Prowess",
        "place": 18
      },
      {
        "player": "Thief_Of_Crowns",
        "deck": "BG",
        "place": 19
      },
      {
        "player": "Terminus0",
        "deck": "Izzet Lessons",
        "place": 20
      },
      {
        "player": "Mldyss",
        "deck": "Izzet Spellementals",
        "place": 21
      },
      {
        "player": "sebastianpozzo",
        "deck": "Bant Ouroboroid",
        "place": 22
      },
      {
        "player": "Kritik",
        "deck": "4c Control",
        "place": 23
      },
      {
        "player": "BERNASTORRES",
        "deck": "Izzet Spellementals",
        "place": 24
      },
      {
        "player": "MultiformatSuperstar",
        "deck": "Izzet Spellementals",
        "place": 25
      },
      {
        "player": "LucasG1ggs",
        "deck": "Mono-Green Landfall",
        "place": 26
      },
      {
        "player": "MacIsaac",
        "deck": "Temur Prowess",
        "place": 27
      },
      {
        "player": "SpockVidaLoka",
        "deck": "Bant Ouroboroid",
        "place": 28
      },
      {
        "player": "makaaaa",
        "deck": "Izzet Prowess",
        "place": 29
      },
      {
        "player": "Venom1",
        "deck": "Mono-Green Landfall",
        "place": 30
      },
      {
        "player": "groot02",
        "deck": "Izzet Lessons",
        "place": 31
      },
      {
        "player": "wolf2222",
        "deck": "Izzet Spellementals",
        "place": 32
      }
    ]
  },
  {
    "date": "2026-03-23",
    "format": "standard",
    "event": "Standard Last Chance 2026-03-23 (1)",
    "url": "https://www.mtggoldfish.com/tournament/62577",
    "players": 32,
    "decklists": [
      {
        "player": "rastaf",
        "deck": "Mono-Green Landfall",
        "place": 1
      },
      {
        "player": "Capriccioso",
        "deck": "Azorius Momo",
        "place": 2
      },
      {
        "player": "eggybenny",
        "deck": "Izzet Prowess",
        "place": 3
      },
      {
        "player": "_Babbuja_",
        "deck": "Dimir Excruciator",
        "place": 4
      },
      {
        "player": "LucasG1ggs",
        "deck": "Mono-Green Landfall",
        "place": 5
      },
      {
        "player": "GTX120",
        "deck": "Mono-White Momo",
        "place": 6
      },
      {
        "player": "Chichichi",
        "deck": "Izzet Spellementals",
        "place": 7
      },
      {
        "player": "ashame",
        "deck": "Izzet Prowess",
        "place": 8
      },
      {
        "player": "indianpancake",
        "deck": "Mono-Green Landfall",
        "place": 9
      },
      {
        "player": "NJ5030",
        "deck": "Izzet Prowess",
        "place": 10
      },
      {
        "player": "VictorEsquici",
        "deck": "Izzet Spellementals",
        "place": 11
      },
      {
        "player": "Salvatto",
        "deck": "Bant Ouroboroid",
        "place": 12
      },
      {
        "player": "CrazyMorango",
        "deck": "Izzet Lessons",
        "place": 13
      },
      {
        "player": "Valimoth",
        "deck": "Izzet Spellementals",
        "place": 14
      },
      {
        "player": "Skeptic2304",
        "deck": "Mono-Green Landfall",
        "place": 15
      },
      {
        "player": "duke12",
        "deck": "4c Harmonizer Combo",
        "place": 16
      },
      {
        "player": "Univerce",
        "deck": "4c Ouroboroid",
        "place": 17
      },
      {
        "player": "Misplacedginger",
        "deck": "Izzet Lessons",
        "place": 18
      },
      {
        "player": "ShadowTitan1",
        "deck": "Bant Ouroboroid",
        "place": 19
      },
      {
        "player": "Merriman",
        "deck": "4c Ouroboroid",
        "place": 20
      },
      {
        "player": "wolf2222",
        "deck": "Izzet Spellementals",
        "place": 21
      },
      {
        "player": "Bruskk",
        "deck": "Izzet Lessons",
        "place": 22
      },
      {
        "player": "Milkshake_",
        "deck": "Izzet Prowess",
        "place": 23
      },
      {
        "player": "Azja",
        "deck": "Izzet Prowess",
        "place": 24
      },
      {
        "player": "L1X0",
        "deck": "Mono-Green Landfall",
        "place": 25
      },
      {
        "player": "Shamplade",
        "deck": "Mono-Green Landfall",
        "place": 26
      },
      {
        "player": "xfile",
        "deck": "Izzet Lessons",
        "place": 27
      },
      {
        "player": "Nocturne_",
        "deck": "Orzhov Midrange",
        "place": 28
      },
      {
        "player": "levunga21",
        "deck": "Dimir Midrange",
        "place": 29
      },
      {
        "player": "sebastianpozzo",
        "deck": "Bant Ouroboroid",
        "place": 30
      },
      {
        "player": "digdude13",
        "deck": "Boros Momo",
        "place": 31
      },
      {
        "player": "PedraStone",
        "deck": "Izzet Lessons",
        "place": 32
      }
    ]
  },
  {
    "date": "2026-03-23",
    "format": "legacy",
    "event": "Legacy Last Chance 2026-03-23",
    "url": "https://www.mtggoldfish.com/tournament/62564",
    "players": 32,
    "decklists": [
      {
        "player": "Thalai",
        "deck": "Colorless",
        "place": 1
      },
      {
        "player": "snoopy-magic",
        "deck": "Sneak and Show",
        "place": 2
      },
      {
        "player": "Otazz",
        "deck": "Sultai Aluren",
        "place": 3
      },
      {
        "player": "_INF_",
        "deck": "Dimir Tempo",
        "place": 4
      },
      {
        "player": "choutin",
        "deck": "Oops! All Spells",
        "place": 5
      },
      {
        "player": "Comrade1312",
        "deck": "Oops! All Spells",
        "place": 6
      },
      {
        "player": "TheGrimLavamancer",
        "deck": "Sneak and Show",
        "place": 7
      },
      {
        "player": "KurumimBagoRosa",
        "deck": "Colorless",
        "place": 8
      },
      {
        "player": "kanican",
        "deck": "UBR",
        "place": 9
      },
      {
        "player": "Vlalutscher",
        "deck": "The EPIC Storm",
        "place": 10
      },
      {
        "player": "Xenowan",
        "deck": "Colorless",
        "place": 11
      },
      {
        "player": "SlayItWithRoses",
        "deck": "Red Stompy",
        "place": 12
      },
      {
        "player": "boytriton",
        "deck": "Colorless",
        "place": 13
      },
      {
        "player": "JohnDoe397",
        "deck": "Death and Taxes (Yorion) - Orzhov",
        "place": 14
      },
      {
        "player": "ReformedPaolo",
        "deck": "Dimir Tempo",
        "place": 15
      },
      {
        "player": "manohito",
        "deck": "Oops! All Spells",
        "place": 16
      },
      {
        "player": "RedArmada",
        "deck": "Dimir Reanimator",
        "place": 17
      },
      {
        "player": "_Batutinha_",
        "deck": "Colorless",
        "place": 18
      },
      {
        "player": "Rhysiner",
        "deck": "BG",
        "place": 19
      },
      {
        "player": "discoverN",
        "deck": "Dimir Tempo",
        "place": 20
      },
      {
        "player": "pepeteam",
        "deck": "Dimir Tempo",
        "place": 21
      },
      {
        "player": "NathanLipetz",
        "deck": "Oops! All Spells",
        "place": 22
      },
      {
        "player": "Munchlax446",
        "deck": "Dimir Tempo",
        "place": 23
      },
      {
        "player": "JV_7777",
        "deck": "Dimir Tempo",
        "place": 24
      },
      {
        "player": "GigaChadSigmaMale",
        "deck": "Dimir Tempo",
        "place": 25
      },
      {
        "player": "zhinonono",
        "deck": "Lands",
        "place": 26
      },
      {
        "player": "clan",
        "deck": "Doomsday",
        "place": 27
      },
      {
        "player": "Ark4n",
        "deck": "Esper Control",
        "place": 28
      },
      {
        "player": "HugoVenda",
        "deck": "Dimir Tempo",
        "place": 29
      },
      {
        "player": "VenusCHN",
        "deck": "Sneak and Show",
        "place": 30
      },
      {
        "player": "Roodslay",
        "deck": "UBG",
        "place": 31
      },
      {
        "player": "Univerce",
        "deck": "Lands",
        "place": 32
      }
    ]
  },
  {
    "date": "2026-03-23",
    "format": "modern",
    "event": "Modern Last Chance 2026-03-23",
    "url": "https://www.mtggoldfish.com/tournament/62560",
    "players": 32,
    "decklists": [
      {
        "player": "kanister",
        "deck": "Amulet Titan",
        "place": 1
      },
      {
        "player": "badgods",
        "deck": "Belcher",
        "place": 2
      },
      {
        "player": "surgetemelo",
        "deck": "Boros Energy",
        "place": 3
      },
      {
        "player": "pizzangry",
        "deck": "Ruby Storm",
        "place": 4
      },
      {
        "player": "sioutis_kk",
        "deck": "Affinity",
        "place": 5
      },
      {
        "player": "WeareVenom",
        "deck": "Amulet Titan",
        "place": 6
      },
      {
        "player": "azax",
        "deck": "Ruby Storm",
        "place": 7
      },
      {
        "player": "JMAK2000",
        "deck": "Mono-Green Tron",
        "place": 8
      },
      {
        "player": "scipios",
        "deck": "Jeskai Control",
        "place": 9
      },
      {
        "player": "Ebnus",
        "deck": "Izzet Prowess",
        "place": 10
      },
      {
        "player": "MTGHolic",
        "deck": "Jeskai Blink",
        "place": 11
      },
      {
        "player": "klien7",
        "deck": "Jeskai Blink",
        "place": 12
      },
      {
        "player": "Capitano_CL",
        "deck": "Ruby Storm",
        "place": 13
      },
      {
        "player": "HugoVenda",
        "deck": "Jeskai Control",
        "place": 14
      },
      {
        "player": "TomCairns",
        "deck": "Dimir Reanimator",
        "place": 15
      },
      {
        "player": "Cachorrowo",
        "deck": "Ruby Storm",
        "place": 16
      },
      {
        "player": "KadettiKersantti",
        "deck": "Grixis Reanimator",
        "place": 17
      },
      {
        "player": "brandi96",
        "deck": "Boros Energy",
        "place": 18
      },
      {
        "player": "Omegauo",
        "deck": "Esper GenericBlink",
        "place": 19
      },
      {
        "player": "toondoslav",
        "deck": "Esper GenericBlink",
        "place": 20
      },
      {
        "player": "GigaChadSigmaMale",
        "deck": "Goryo&#39;s Vengeance",
        "place": 21
      },
      {
        "player": "pepeteam",
        "deck": "Dimir Midrange",
        "place": 22
      },
      {
        "player": "Univerce",
        "deck": "Affinity",
        "place": 23
      },
      {
        "player": "chengyiw",
        "deck": "Goryo&#39;s Vengeance",
        "place": 24
      },
      {
        "player": "felider",
        "deck": "Jeskai Blink",
        "place": 25
      },
      {
        "player": "FakeShaver",
        "deck": "Belcher",
        "place": 26
      },
      {
        "player": "Athenani",
        "deck": "Boros Energy",
        "place": 27
      },
      {
        "player": "JPA93",
        "deck": "Neobrand",
        "place": 28
      },
      {
        "player": "Terminus0",
        "deck": "Esper GenericBlink",
        "place": 29
      },
      {
        "player": "Gerschi",
        "deck": "Living End",
        "place": 30
      },
      {
        "player": "Venom1",
        "deck": "Jeskai Blink",
        "place": 31
      },
      {
        "player": "bless_von",
        "deck": "Boros Energy",
        "place": 32
      }
    ]
  },
  {
    "date": "2026-03-23",
    "format": "standard",
    "event": "Standard Last Chance 2026-03-23",
    "url": "https://www.mtggoldfish.com/tournament/62557",
    "players": 32,
    "decklists": [
      {
        "player": "rastaf",
        "deck": "Mono-Green Landfall",
        "place": 1
      },
      {
        "player": "Capriccioso",
        "deck": "Azorius Momo",
        "place": 2
      },
      {
        "player": "eggybenny",
        "deck": "Izzet Prowess",
        "place": 3
      },
      {
        "player": "_Babbuja_",
        "deck": "Dimir Excruciator",
        "place": 4
      },
      {
        "player": "LucasG1ggs",
        "deck": "Mono-Green Landfall",
        "place": 5
      },
      {
        "player": "GTX120",
        "deck": "Mono-White Momo",
        "place": 6
      },
      {
        "player": "Chichichi",
        "deck": "Izzet Spellementals",
        "place": 7
      },
      {
        "player": "ashame",
        "deck": "Izzet Prowess",
        "place": 8
      },
      {
        "player": "indianpancake",
        "deck": "Mono-Green Landfall",
        "place": 9
      },
      {
        "player": "NJ5030",
        "deck": "Izzet Prowess",
        "place": 10
      },
      {
        "player": "VictorEsquici",
        "deck": "Izzet Spellementals",
        "place": 11
      },
      {
        "player": "Salvatto",
        "deck": "Bant Ouroboroid",
        "place": 12
      },
      {
        "player": "CrazyMorango",
        "deck": "Izzet Lessons",
        "place": 13
      },
      {
        "player": "Valimoth",
        "deck": "Izzet Spellementals",
        "place": 14
      },
      {
        "player": "Skeptic2304",
        "deck": "Mono-Green Landfall",
        "place": 15
      },
      {
        "player": "duke12",
        "deck": "4c Harmonizer Combo",
        "place": 16
      },
      {
        "player": "Univerce",
        "deck": "4c Ouroboroid",
        "place": 17
      },
      {
        "player": "Misplacedginger",
        "deck": "Izzet Lessons",
        "place": 18
      },
      {
        "player": "ShadowTitan1",
        "deck": "Bant Ouroboroid",
        "place": 19
      },
      {
        "player": "Merriman",
        "deck": "4c Ouroboroid",
        "place": 20
      },
      {
        "player": "wolf2222",
        "deck": "Izzet Spellementals",
        "place": 21
      },
      {
        "player": "Bruskk",
        "deck": "Izzet Lessons",
        "place": 22
      },
      {
        "player": "Milkshake_",
        "deck": "Izzet Prowess",
        "place": 23
      },
      {
        "player": "Azja",
        "deck": "Izzet Prowess",
        "place": 24
      },
      {
        "player": "L1X0",
        "deck": "Mono-Green Landfall",
        "place": 25
      },
      {
        "player": "Shamplade",
        "deck": "Mono-Green Landfall",
        "place": 26
      },
      {
        "player": "xfile",
        "deck": "Izzet Lessons",
        "place": 27
      },
      {
        "player": "Nocturne_",
        "deck": "Orzhov Midrange",
        "place": 28
      },
      {
        "player": "levunga21",
        "deck": "Dimir Midrange",
        "place": 29
      },
      {
        "player": "sebastianpozzo",
        "deck": "Bant Ouroboroid",
        "place": 30
      },
      {
        "player": "digdude13",
        "deck": "Boros Momo",
        "place": 31
      },
      {
        "player": "PedraStone",
        "deck": "Izzet Lessons",
        "place": 32
      }
    ]
  },
  {
    "date": "2026-03-22",
    "format": "modern",
    "event": "Modern Last Chance 2026-03-22 (1)",
    "url": "https://www.mtggoldfish.com/tournament/62588",
    "players": 32,
    "decklists": [
      {
        "player": "ETBJezus",
        "deck": "Dimir Midrange",
        "place": 1
      },
      {
        "player": "xDingusKhan",
        "deck": "Ruby Storm",
        "place": 2
      },
      {
        "player": "Laplasjan",
        "deck": "Jeskai Blink",
        "place": 3
      },
      {
        "player": "Pmizz",
        "deck": "Jeskai Blink",
        "place": 4
      },
      {
        "player": "eclipse4343",
        "deck": "Azorius Control",
        "place": 5
      },
      {
        "player": "O_danielakos",
        "deck": "Temur Prowess",
        "place": 6
      },
      {
        "player": "Crovax90",
        "deck": "Jeskai Blink",
        "place": 7
      },
      {
        "player": "RUBAO_oDonoDoMundo",
        "deck": "Ruby Storm",
        "place": 8
      },
      {
        "player": "Yarfangel",
        "deck": "Jeskai Blink",
        "place": 9
      },
      {
        "player": "Moorehardcore",
        "deck": "Yawgmoth",
        "place": 10
      },
      {
        "player": "Univerce",
        "deck": "Affinity",
        "place": 11
      },
      {
        "player": "sioutis_kk",
        "deck": "Affinity",
        "place": 12
      },
      {
        "player": "Xerk",
        "deck": "Yawgmoth",
        "place": 13
      },
      {
        "player": "cigarettesaftershrek",
        "deck": "Affinity",
        "place": 14
      },
      {
        "player": "sokos13",
        "deck": "Jeskai Blink",
        "place": 15
      },
      {
        "player": "toondoslav",
        "deck": "Esper GenericBlink",
        "place": 16
      },
      {
        "player": "Nilsfit",
        "deck": "Jeskai Control",
        "place": 17
      },
      {
        "player": "Napoleon_I",
        "deck": "Naya Energy",
        "place": 18
      },
      {
        "player": "Cazuza",
        "deck": "Jeskai Blink",
        "place": 19
      },
      {
        "player": "mendyourheart",
        "deck": "Domain Zoo",
        "place": 20
      },
      {
        "player": "DemonicTutors",
        "deck": "Yawgmoth",
        "place": 21
      },
      {
        "player": "Foxantes",
        "deck": "Boros Energy",
        "place": 22
      },
      {
        "player": "Venom1",
        "deck": "Jeskai Blink",
        "place": 23
      },
      {
        "player": "pottinkx",
        "deck": "Boros Energy",
        "place": 24
      },
      {
        "player": "applefox",
        "deck": "Living End",
        "place": 25
      },
      {
        "player": "MultiformatSuperstar",
        "deck": "Neobrand",
        "place": 26
      },
      {
        "player": "J4K3ST3R02",
        "deck": "Affinity",
        "place": 27
      },
      {
        "player": "LucasG1ggs",
        "deck": "Boros Energy",
        "place": 28
      },
      {
        "player": "Xenowan",
        "deck": "Neobrand",
        "place": 29
      },
      {
        "player": "aspiringspike",
        "deck": "Dimir Midrange",
        "place": 30
      },
      {
        "player": "tibalt_of_red_sub",
        "deck": "Dimir Mill",
        "place": 31
      },
      {
        "player": "Misplacedginger",
        "deck": "Jeskai Blink",
        "place": 32
      }
    ]
  },
  {
    "date": "2026-03-22",
    "format": "modern",
    "event": "Modern Last Chance 2026-03-22",
    "url": "https://www.mtggoldfish.com/tournament/62540",
    "players": 32,
    "decklists": [
      {
        "player": "ETBJezus",
        "deck": "Dimir Midrange",
        "place": 1
      },
      {
        "player": "xDingusKhan",
        "deck": "Ruby Storm",
        "place": 2
      },
      {
        "player": "Laplasjan",
        "deck": "Jeskai Blink",
        "place": 3
      },
      {
        "player": "Pmizz",
        "deck": "Jeskai Blink",
        "place": 4
      },
      {
        "player": "eclipse4343",
        "deck": "Azorius Control",
        "place": 5
      },
      {
        "player": "O_danielakos",
        "deck": "Temur Prowess",
        "place": 6
      },
      {
        "player": "Crovax90",
        "deck": "Jeskai Blink",
        "place": 7
      },
      {
        "player": "RUBAO_oDonoDoMundo",
        "deck": "Ruby Storm",
        "place": 8
      },
      {
        "player": "Yarfangel",
        "deck": "Jeskai Blink",
        "place": 9
      },
      {
        "player": "Moorehardcore",
        "deck": "Yawgmoth",
        "place": 10
      },
      {
        "player": "Univerce",
        "deck": "Affinity",
        "place": 11
      },
      {
        "player": "sioutis_kk",
        "deck": "Affinity",
        "place": 12
      },
      {
        "player": "Xerk",
        "deck": "Yawgmoth",
        "place": 13
      },
      {
        "player": "cigarettesaftershrek",
        "deck": "Affinity",
        "place": 14
      },
      {
        "player": "sokos13",
        "deck": "Jeskai Blink",
        "place": 15
      },
      {
        "player": "toondoslav",
        "deck": "Esper GenericBlink",
        "place": 16
      },
      {
        "player": "Nilsfit",
        "deck": "Jeskai Control",
        "place": 17
      },
      {
        "player": "Napoleon_I",
        "deck": "Naya Energy",
        "place": 18
      },
      {
        "player": "Cazuza",
        "deck": "Jeskai Blink",
        "place": 19
      },
      {
        "player": "mendyourheart",
        "deck": "Domain Zoo",
        "place": 20
      },
      {
        "player": "DemonicTutors",
        "deck": "Yawgmoth",
        "place": 21
      },
      {
        "player": "Foxantes",
        "deck": "Boros Energy",
        "place": 22
      },
      {
        "player": "Venom1",
        "deck": "Jeskai Blink",
        "place": 23
      },
      {
        "player": "pottinkx",
        "deck": "Boros Energy",
        "place": 24
      },
      {
        "player": "applefox",
        "deck": "Living End",
        "place": 25
      },
      {
        "player": "MultiformatSuperstar",
        "deck": "Neobrand",
        "place": 26
      },
      {
        "player": "J4K3ST3R02",
        "deck": "Affinity",
        "place": 27
      },
      {
        "player": "LucasG1ggs",
        "deck": "Boros Energy",
        "place": 28
      },
      {
        "player": "Xenowan",
        "deck": "Neobrand",
        "place": 29
      },
      {
        "player": "aspiringspike",
        "deck": "Dimir Midrange",
        "place": 30
      },
      {
        "player": "tibalt_of_red_sub",
        "deck": "Dimir Mill",
        "place": 31
      },
      {
        "player": "Misplacedginger",
        "deck": "Jeskai Blink",
        "place": 32
      }
    ]
  },
  {
    "date": "2025-12-03",
    "format": "legacy",
    "event": "Legacy Last Chance 2025-12-03",
    "url": "https://www.mtggoldfish.com/tournament/60075",
    "players": 32,
    "decklists": [
      {
        "player": "TristanJWL",
        "deck": "Izzet Delver",
        "place": 1
      },
      {
        "player": "_INF_",
        "deck": "Izzet Delver",
        "place": 2
      },
      {
        "player": "kanister",
        "deck": "Mystic Forge Combo",
        "place": 3
      },
      {
        "player": "LasVegasChaos",
        "deck": "UBRG",
        "place": 4
      },
      {
        "player": "8salazzar8",
        "deck": "Red Stompy",
        "place": 5
      },
      {
        "player": "zhinonono",
        "deck": "Abzan",
        "place": 6
      },
      {
        "player": "The_shallow_grave",
        "deck": "Jeskai Control",
        "place": 7
      },
      {
        "player": "felix619",
        "deck": "Dimir Tempo",
        "place": 8
      },
      {
        "player": "James_Zhi",
        "deck": "Abzan",
        "place": 9
      },
      {
        "player": "clan",
        "deck": "Doomsday",
        "place": 10
      },
      {
        "player": "qtaro",
        "deck": "Eldrazi",
        "place": 11
      },
      {
        "player": "ajdadd420",
        "deck": "Stiflenought",
        "place": 12
      },
      {
        "player": "NathanOfTheGiltLeaf",
        "deck": "Dimir Tempo",
        "place": 13
      },
      {
        "player": "Talking1804",
        "deck": "Eldrazi",
        "place": 14
      },
      {
        "player": "badgods",
        "deck": "Eldrazi",
        "place": 15
      },
      {
        "player": "RyanWu",
        "deck": "Grixis Control",
        "place": 16
      },
      {
        "player": "jankyb",
        "deck": "Jeskai Control",
        "place": 17
      },
      {
        "player": "kenjinsakura",
        "deck": "Izzet Delver",
        "place": 18
      },
      {
        "player": "Supercazzola",
        "deck": "Izzet Delver",
        "place": 19
      },
      {
        "player": "ziofrancone",
        "deck": "Dimir Tempo",
        "place": 20
      },
      {
        "player": "Meltiin",
        "deck": "Izzet Artifacts",
        "place": 21
      },
      {
        "player": "RedArmada",
        "deck": "Dimir Tempo",
        "place": 22
      },
      {
        "player": "peposhi",
        "deck": "UG",
        "place": 23
      },
      {
        "player": "DMianete",
        "deck": "Izzet Delver",
        "place": 24
      },
      {
        "player": "iamyep",
        "deck": "Dimir Tempo",
        "place": 25
      },
      {
        "player": "_Shatun_",
        "deck": "Dimir Tempo",
        "place": 26
      },
      {
        "player": "Kjwallace",
        "deck": "Omni-Tell",
        "place": 27
      },
      {
        "player": "FynnOfBlood",
        "deck": "Omni-Tell",
        "place": 28
      },
      {
        "player": "MultiformatSuperstar",
        "deck": "UB",
        "place": 29
      },
      {
        "player": "okarin_",
        "deck": "Doomsday",
        "place": 30
      },
      {
        "player": "Depian",
        "deck": "Affinity Stompy",
        "place": 31
      },
      {
        "player": "Ark4n",
        "deck": "Grixis Control",
        "place": 32
      }
    ]
  },
  {
    "date": "2025-12-03",
    "format": "standard",
    "event": "Standard Last Chance 2025-12-03",
    "url": "https://www.mtggoldfish.com/tournament/60073",
    "players": 32,
    "decklists": [
      {
        "player": "marceliiine",
        "deck": "WU",
        "place": 1
      },
      {
        "player": "Salvatto",
        "deck": "Izzet Looting",
        "place": 2
      },
      {
        "player": "Cachorrowo",
        "deck": "Azorius Control",
        "place": 3
      },
      {
        "player": "rastaf",
        "deck": "Izzet Looting",
        "place": 4
      },
      {
        "player": "ShadowTitan1",
        "deck": "Izzet Prowess",
        "place": 5
      },
      {
        "player": "duanceyao",
        "deck": "Izzet Looting",
        "place": 6
      },
      {
        "player": "FletcherPullUp",
        "deck": "Bant Airbending Combo",
        "place": 7
      },
      {
        "player": "MultiformatSuperstar",
        "deck": "Simic Aggro",
        "place": 8
      },
      {
        "player": "ashame",
        "deck": "Simic Aggro",
        "place": 9
      },
      {
        "player": "mei0024",
        "deck": "Izzet Prowess",
        "place": 10
      },
      {
        "player": "peter780108",
        "deck": "Izzet Prowess",
        "place": 11
      },
      {
        "player": "LucasG1ggs",
        "deck": "Izzet Looting",
        "place": 12
      },
      {
        "player": "cavedan",
        "deck": "UG",
        "place": 13
      },
      {
        "player": "Capriccioso",
        "deck": "Izzet Prowess",
        "place": 14
      },
      {
        "player": "Thronhart",
        "deck": "Izzet Looting",
        "place": 15
      },
      {
        "player": "XantosCell",
        "deck": "Izzet Prowess",
        "place": 16
      },
      {
        "player": "Ivan_Draw_Go",
        "deck": "Dimir Midrange",
        "place": 17
      },
      {
        "player": "WaffleWiz",
        "deck": "Mono-Red Aggro",
        "place": 18
      },
      {
        "player": "Giox96",
        "deck": "Mono-Red Aggro",
        "place": 19
      },
      {
        "player": "D00mwake",
        "deck": "Esper Self-Bounce",
        "place": 20
      },
      {
        "player": "Azja",
        "deck": "Izzet Looting",
        "place": 21
      },
      {
        "player": "GinkoHS",
        "deck": "4c Insidious Roots",
        "place": 22
      },
      {
        "player": "Manny-",
        "deck": "Dimir Midrange",
        "place": 23
      },
      {
        "player": "RNAPBP1",
        "deck": "Sultai Reanimator",
        "place": 24
      },
      {
        "player": "Lord_Beerus",
        "deck": "Mono-Red Aggro",
        "place": 25
      },
      {
        "player": "Relieve",
        "deck": "UR",
        "place": 26
      },
      {
        "player": "il_matagatto",
        "deck": "Mono-White Enchantments",
        "place": 27
      },
      {
        "player": "Aardos",
        "deck": "Jeskai Control",
        "place": 28
      },
      {
        "player": "Skeptic2304",
        "deck": "Jeskai Control",
        "place": 29
      },
      {
        "player": "Xwhale",
        "deck": "Dimir Self-Bounce",
        "place": 30
      },
      {
        "player": "HoldTheElle",
        "deck": "Dimir Self-Bounce",
        "place": 31
      },
      {
        "player": "Richie727",
        "deck": "Jeskai Control",
        "place": 32
      }
    ]
  },
  {
    "date": "2025-12-02",
    "format": "legacy",
    "event": "Legacy Last Chance 2025-12-02 (1)",
    "url": "https://www.mtggoldfish.com/tournament/60062",
    "players": 32,
    "decklists": [
      {
        "player": "Foxantes",
        "deck": "Red Stompy",
        "place": 1
      },
      {
        "player": "Antarctica",
        "deck": "Izzet Delver",
        "place": 2
      },
      {
        "player": "mei0024",
        "deck": "UB",
        "place": 3
      },
      {
        "player": "DNSolver",
        "deck": "Eldrazi",
        "place": 4
      },
      {
        "player": "Munchlax446",
        "deck": "Oops! All Spells",
        "place": 5
      },
      {
        "player": "meanfannypack",
        "deck": "Death and Taxes (Yorion) - Abzan",
        "place": 6
      },
      {
        "player": "MultiformatSuperstar",
        "deck": "Omni-Tell",
        "place": 7
      },
      {
        "player": "_Shatun_",
        "deck": "Dimir Tempo",
        "place": 8
      },
      {
        "player": "Xenowan",
        "deck": "Omni-Tell",
        "place": 9
      },
      {
        "player": "SknerusMcKwacz",
        "deck": "Oops! All Spells",
        "place": 10
      },
      {
        "player": "okarin_",
        "deck": "Doomsday",
        "place": 11
      },
      {
        "player": "ziofrancone",
        "deck": "Dimir Tempo",
        "place": 12
      },
      {
        "player": "MahfuzVanGogh",
        "deck": "LED Dredge",
        "place": 13
      },
      {
        "player": "hellonewton",
        "deck": "Cradle Control",
        "place": 14
      },
      {
        "player": "hundinggjornersen",
        "deck": "Esper Vial",
        "place": 15
      },
      {
        "player": "LukeBrandes",
        "deck": "Omni-Tell",
        "place": 16
      },
      {
        "player": "SuperCow12653",
        "deck": "Grixis Control",
        "place": 17
      },
      {
        "player": "ho-oh",
        "deck": "Mystic Forge Combo",
        "place": 18
      },
      {
        "player": "littledarwin",
        "deck": "Stiflenought",
        "place": 19
      },
      {
        "player": "ZYX-FXY",
        "deck": "BR",
        "place": 20
      },
      {
        "player": "qtaro",
        "deck": "Eldrazi",
        "place": 21
      },
      {
        "player": "mizzafizza",
        "deck": "Dimir Tempo",
        "place": 22
      },
      {
        "player": "ecobaronen",
        "deck": "Jeskai Control",
        "place": 23
      },
      {
        "player": "kozz27",
        "deck": "Naya Initiative",
        "place": 24
      },
      {
        "player": "FunkiMunki",
        "deck": "UB",
        "place": 25
      },
      {
        "player": "Genericcactus",
        "deck": "Death and Taxes (Yorion) - Abzan",
        "place": 26
      },
      {
        "player": "joker10289",
        "deck": "Omni-Tell",
        "place": 27
      },
      {
        "player": "Sharkcaster_Mage",
        "deck": "Dimir Cloudpost",
        "place": 28
      },
      {
        "player": "Univerce",
        "deck": "Oops! All Spells",
        "place": 29
      },
      {
        "player": "Erik157751",
        "deck": "Sneak and Show",
        "place": 30
      },
      {
        "player": "B-Carp",
        "deck": "Izzet Delver",
        "place": 31
      },
      {
        "player": "pirol94",
        "deck": "Mystic Forge Combo",
        "place": 32
      }
    ]
  },
  {
    "date": "2025-12-02",
    "format": "modern",
    "event": "Modern Last Chance 2025-12-02 (1)",
    "url": "https://www.mtggoldfish.com/tournament/60061",
    "players": 32,
    "decklists": [
      {
        "player": "WrzoBuSeks",
        "deck": "Domain Zoo",
        "place": 1
      },
      {
        "player": "Lord_of_The_Wastes",
        "deck": "Belcher",
        "place": 2
      },
      {
        "player": "LordEgg",
        "deck": "Affinity",
        "place": 3
      },
      {
        "player": "Darthkid",
        "deck": "WR",
        "place": 4
      },
      {
        "player": "Savior0117",
        "deck": "Belcher",
        "place": 5
      },
      {
        "player": "ZVendetta",
        "deck": "Boros Energy",
        "place": 6
      },
      {
        "player": "Salvatto",
        "deck": "Eldrazi Ramp",
        "place": 7
      },
      {
        "player": "filpin",
        "deck": "Amulet Titan",
        "place": 8
      },
      {
        "player": "McWinSauce",
        "deck": "Jeskai Blink",
        "place": 9
      },
      {
        "player": "KangXiaotian",
        "deck": "Esper Midrange",
        "place": 10
      },
      {
        "player": "ncowden",
        "deck": "Jeskai Control",
        "place": 11
      },
      {
        "player": "Zompatanfo",
        "deck": "Affinity",
        "place": 12
      },
      {
        "player": "LucasG1ggs",
        "deck": "WR",
        "place": 13
      },
      {
        "player": "MultiformatSuperstar",
        "deck": "Yawgmoth",
        "place": 14
      },
      {
        "player": "Odin2015",
        "deck": "Eldrazi Ramp",
        "place": 15
      },
      {
        "player": "Takayama",
        "deck": "Neobrand",
        "place": 16
      },
      {
        "player": "MagicDevil666",
        "deck": "Tron",
        "place": 17
      },
      {
        "player": "CheeseCakey",
        "deck": "Ruby Storm",
        "place": 18
      },
      {
        "player": "Deathnote1999",
        "deck": "Affinity",
        "place": 19
      },
      {
        "player": "peter780108",
        "deck": "Jeskai Energy",
        "place": 20
      },
      {
        "player": "Curtisaxel",
        "deck": "Boros Energy",
        "place": 21
      },
      {
        "player": "AlpInco",
        "deck": "Affinity",
        "place": 22
      },
      {
        "player": "Do0mSwitch",
        "deck": "Jeskai Control",
        "place": 23
      },
      {
        "player": "Slatorade",
        "deck": "Ruby Storm",
        "place": 24
      },
      {
        "player": "jontih",
        "deck": "The Rock",
        "place": 25
      },
      {
        "player": "MCScards",
        "deck": "Boros Energy",
        "place": 26
      },
      {
        "player": "mei0024",
        "deck": "RG",
        "place": 27
      },
      {
        "player": "Frejat",
        "deck": "Izzet Steel-Cutter",
        "place": 28
      },
      {
        "player": "TekiAkuma",
        "deck": "Domain Zoo",
        "place": 29
      },
      {
        "player": "Suechtler",
        "deck": "Temur Prowess",
        "place": 30
      },
      {
        "player": "Selfeisek",
        "deck": "Mono-Black Midrange",
        "place": 31
      },
      {
        "player": "_Batutinha_",
        "deck": "Jeskai Midrange",
        "place": 32
      }
    ]
  },
  {
    "date": "2025-12-02",
    "format": "standard",
    "event": "Standard Last Chance 2025-12-02",
    "url": "https://www.mtggoldfish.com/tournament/60053",
    "players": 32,
    "decklists": [
      {
        "player": "O_danielakos",
        "deck": "Dimir Midrange",
        "place": 1
      },
      {
        "player": "komattaman",
        "deck": "Izzet Prowess",
        "place": 2
      },
      {
        "player": "TheManLand",
        "deck": "Izzet Looting",
        "place": 3
      },
      {
        "player": "Bosseidon",
        "deck": "Boros Leyline Aggro",
        "place": 4
      },
      {
        "player": "meanfannypack",
        "deck": "Sultai Reanimator",
        "place": 5
      },
      {
        "player": "brandi96",
        "deck": "Bant Airbending Combo",
        "place": 6
      },
      {
        "player": "HazuhiroNakamura",
        "deck": "UR",
        "place": 7
      },
      {
        "player": "Salvatto",
        "deck": "Izzet Looting",
        "place": 8
      },
      {
        "player": "LucasG1ggs",
        "deck": "Izzet Looting",
        "place": 9
      },
      {
        "player": "Giovane_Lupo",
        "deck": "Temur Floodcaller Combo",
        "place": 10
      },
      {
        "player": "rastaf",
        "deck": "Izzet Looting",
        "place": 11
      },
      {
        "player": "makkako",
        "deck": "4c Reanimator",
        "place": 12
      },
      {
        "player": "cicciogire",
        "deck": "Dimir Midrange",
        "place": 13
      },
      {
        "player": "Chichichi",
        "deck": "Rakdos Viper",
        "place": 14
      },
      {
        "player": "Gitaxian_Probe",
        "deck": "Izzet Lessons",
        "place": 15
      },
      {
        "player": "Varo",
        "deck": "Izzet Looting",
        "place": 16
      },
      {
        "player": "ziofrancone",
        "deck": "Izzet Looting",
        "place": 17
      },
      {
        "player": "elBB",
        "deck": "Esper Self-Bounce",
        "place": 18
      },
      {
        "player": "MTGHolic",
        "deck": "Izzet Looting",
        "place": 19
      },
      {
        "player": "optivial",
        "deck": "Izzet Lessons",
        "place": 20
      },
      {
        "player": "bomberboss",
        "deck": "Jeskai Control",
        "place": 21
      },
      {
        "player": "manohito",
        "deck": "Izzet Prowess",
        "place": 22
      },
      {
        "player": "Dai66s",
        "deck": "Dimir Self-Bounce",
        "place": 23
      },
      {
        "player": "CuteChandra19",
        "deck": "Boros Manufacturing",
        "place": 24
      },
      {
        "player": "OlonJohnson",
        "deck": "Dimir Self-Bounce",
        "place": 25
      },
      {
        "player": "marcofabrizi",
        "deck": "Izzet Looting",
        "place": 26
      },
      {
        "player": "SanPop",
        "deck": "Sultai Reanimator",
        "place": 27
      },
      {
        "player": "Aardos",
        "deck": "Bant Airbending Combo",
        "place": 28
      },
      {
        "player": "Junkmener",
        "deck": "UG",
        "place": 29
      },
      {
        "player": "moreno13",
        "deck": "Izzet Looting",
        "place": 30
      },
      {
        "player": "Anonymous",
        "deck": "Sultai Reanimator",
        "place": 31
      },
      {
        "player": "FunkyBrewster",
        "deck": "Mono-Red Aggro",
        "place": 32
      }
    ]
  },
  {
    "date": "2025-12-02",
    "format": "legacy",
    "event": "Legacy Last Chance 2025-12-02",
    "url": "https://www.mtggoldfish.com/tournament/60052",
    "players": 32,
    "decklists": [
      {
        "player": "RPSbonjwa",
        "deck": "Izzet Delver",
        "place": 1
      },
      {
        "player": "HoldTheElle",
        "deck": "Mystic Forge Combo",
        "place": 2
      },
      {
        "player": "Munchlax446",
        "deck": "Oops! All Spells",
        "place": 3
      },
      {
        "player": "xDingusKhan",
        "deck": "Oops! All Spells",
        "place": 4
      },
      {
        "player": "TonyScapone",
        "deck": "U",
        "place": 5
      },
      {
        "player": "CaptainAfrica",
        "deck": "Loam Pox",
        "place": 6
      },
      {
        "player": "RyanWu",
        "deck": "Grixis Control",
        "place": 7
      },
      {
        "player": "ecobaronen",
        "deck": "UB",
        "place": 8
      },
      {
        "player": "jankyb",
        "deck": "Jeskai Control",
        "place": 9
      },
      {
        "player": "DMianete",
        "deck": "Izzet Delver",
        "place": 10
      },
      {
        "player": "Joyfulwaffle",
        "deck": "Dimir Delver",
        "place": 11
      },
      {
        "player": "Cachorrowo",
        "deck": "Oops! All Spells",
        "place": 12
      },
      {
        "player": "GoblinK1ng",
        "deck": "UBR",
        "place": 13
      },
      {
        "player": "Lord_Beerus",
        "deck": "Izzet Delver",
        "place": 14
      },
      {
        "player": "Shadowz2005",
        "deck": "Izzet Delver",
        "place": 15
      },
      {
        "player": "Ozymandias17",
        "deck": "Dimir Tempo",
        "place": 16
      },
      {
        "player": "choutin",
        "deck": "Oops! All Spells",
        "place": 17
      },
      {
        "player": "JPA93",
        "deck": "Sneak and Show",
        "place": 18
      },
      {
        "player": "Manny-",
        "deck": "Affinity Stompy",
        "place": 19
      },
      {
        "player": "harmonywoods",
        "deck": "Esper Control",
        "place": 20
      },
      {
        "player": "parkss",
        "deck": "Dimir Tempo",
        "place": 21
      },
      {
        "player": "ZYX-FXY",
        "deck": "Sneak and Show",
        "place": 22
      },
      {
        "player": "SuperCow12653",
        "deck": "Grixis Control",
        "place": 23
      },
      {
        "player": "SauTay",
        "deck": "Grixis Tempo",
        "place": 24
      },
      {
        "player": "MahfuzVanGogh",
        "deck": "LED Dredge",
        "place": 25
      },
      {
        "player": "ho-oh",
        "deck": "Mystic Forge Combo",
        "place": 26
      },
      {
        "player": "ashame",
        "deck": "Eldrazi",
        "place": 27
      },
      {
        "player": "jready",
        "deck": "Omni-Tell",
        "place": 28
      },
      {
        "player": "ayukawa",
        "deck": "Izzet Delver",
        "place": 29
      },
      {
        "player": "kozz27",
        "deck": "Naya Initiative",
        "place": 30
      },
      {
        "player": "BalenciagaNBoba",
        "deck": "Jeskai Stoneblade",
        "place": 31
      },
      {
        "player": "EmperorOppai",
        "deck": "Dimir Tempo",
        "place": 32
      }
    ]
  },
  {
    "date": "2025-12-02",
    "format": "modern",
    "event": "Modern Last Chance 2025-12-02",
    "url": "https://www.mtggoldfish.com/tournament/60049",
    "players": 32,
    "decklists": [
      {
        "player": "barczek",
        "deck": "Yawgmoth",
        "place": 1
      },
      {
        "player": "TingInTheRice",
        "deck": "5c Midrange",
        "place": 2
      },
      {
        "player": "E90_DeliveryBoy",
        "deck": "Belcher",
        "place": 3
      },
      {
        "player": "ashame",
        "deck": "Jeskai Blink",
        "place": 4
      },
      {
        "player": "trogdor1396",
        "deck": "Jeskai Blink",
        "place": 5
      },
      {
        "player": "_Batutinha_",
        "deck": "Jeskai Energy",
        "place": 6
      },
      {
        "player": "1OR513N86",
        "deck": "Grixis Reanimator",
        "place": 7
      },
      {
        "player": "Omegauo",
        "deck": "Esper GenericBlink",
        "place": 8
      },
      {
        "player": "Odin2015",
        "deck": "Eldrazi Ramp",
        "place": 9
      },
      {
        "player": "McWinSauce",
        "deck": "Jeskai Blink",
        "place": 10
      },
      {
        "player": "Filho_do_MOL",
        "deck": "Ruby Storm",
        "place": 11
      },
      {
        "player": "AquileX7",
        "deck": "Jeskai Blink",
        "place": 12
      },
      {
        "player": "fclyra",
        "deck": "Yawgmoth",
        "place": 13
      },
      {
        "player": "Boucha",
        "deck": "Amulet Titan",
        "place": 14
      },
      {
        "player": "funnyscreenname",
        "deck": "Domain Zoo",
        "place": 15
      },
      {
        "player": "nahuel10",
        "deck": "Temur Prowess",
        "place": 16
      },
      {
        "player": "MixolydianMagus",
        "deck": "Izzet Steel-Cutter",
        "place": 17
      },
      {
        "player": "Magicofplayer1",
        "deck": "Temur Prowess",
        "place": 18
      },
      {
        "player": "Manny-",
        "deck": "Ruby Storm",
        "place": 19
      },
      {
        "player": "O_danielakos",
        "deck": "Izzet Prowess",
        "place": 20
      },
      {
        "player": "SupremePete56",
        "deck": "Boros Energy",
        "place": 21
      },
      {
        "player": "TheColorOfBoom",
        "deck": "WR",
        "place": 22
      },
      {
        "player": "YungDingo",
        "deck": "Yawgmoth",
        "place": 23
      },
      {
        "player": "teruteru8140",
        "deck": "Boros Energy",
        "place": 24
      },
      {
        "player": "_IlNano_",
        "deck": "Goryo&#39;s Vengeance",
        "place": 25
      },
      {
        "player": "KillerWhale01",
        "deck": "WR",
        "place": 26
      },
      {
        "player": "Hamuda",
        "deck": "Izzet Prowess",
        "place": 27
      },
      {
        "player": "_Babbuja_",
        "deck": "Jeskai Energy",
        "place": 28
      },
      {
        "player": "FranBenitez91",
        "deck": "Eldrazi Tron",
        "place": 29
      },
      {
        "player": "Gitaxian_Probe",
        "deck": "WR",
        "place": 30
      },
      {
        "player": "Salvatto",
        "deck": "Boros Energy",
        "place": 31
      },
      {
        "player": "Selfeisek",
        "deck": "Mono-Black Midrange",
        "place": 32
      }
    ]
  },
  {
    "date": "2025-12-01",
    "format": "standard",
    "event": "Standard Last Chance 2025-12-01 (1)",
    "url": "https://www.mtggoldfish.com/tournament/60038",
    "players": 32,
    "decklists": [
      {
        "player": "mosh_joscoe",
        "deck": "Izzet Lessons",
        "place": 1
      },
      {
        "player": "Gerardo94",
        "deck": "Izzet Looting",
        "place": 2
      },
      {
        "player": "MKC",
        "deck": "Simic Aggro",
        "place": 3
      },
      {
        "player": "Asbrinkvun",
        "deck": "Jeskai Control",
        "place": 4
      },
      {
        "player": "Lillia",
        "deck": "Bant Airbending Combo",
        "place": 5
      },
      {
        "player": "marcofabrizi",
        "deck": "Dimir Midrange",
        "place": 6
      },
      {
        "player": "Nozynski",
        "deck": "4c Reanimator",
        "place": 7
      },
      {
        "player": "HolaChico",
        "deck": "Sultai Reanimator",
        "place": 8
      },
      {
        "player": "O_danielakos",
        "deck": "Dimir Midrange",
        "place": 9
      },
      {
        "player": "surgetemelo",
        "deck": "Izzet Looting",
        "place": 10
      },
      {
        "player": "Univerce",
        "deck": "Bant Airbending Combo",
        "place": 11
      },
      {
        "player": "duanceyao",
        "deck": "Izzet Looting",
        "place": 12
      },
      {
        "player": "choobes",
        "deck": "Izzet Lessons",
        "place": 13
      },
      {
        "player": "Varo",
        "deck": "Izzet Looting",
        "place": 14
      },
      {
        "player": "L1X0",
        "deck": "Simic Aggro",
        "place": 15
      },
      {
        "player": "_IlNano_",
        "deck": "Izzet Looting",
        "place": 16
      },
      {
        "player": "SargonVito8",
        "deck": "Azorius Control",
        "place": 17
      },
      {
        "player": "BeoulveHeart",
        "deck": "4c Artifacts",
        "place": 18
      },
      {
        "player": "kthanakit26",
        "deck": "Dimir Self-Bounce",
        "place": 19
      },
      {
        "player": "cavedan",
        "deck": "BG",
        "place": 20
      },
      {
        "player": "rastaf",
        "deck": "Izzet Looting",
        "place": 21
      },
      {
        "player": "Koala40",
        "deck": "Temur Floodcaller Combo",
        "place": 22
      },
      {
        "player": "Gerschi",
        "deck": "Simic Aggro",
        "place": 23
      },
      {
        "player": "cicciogire",
        "deck": "Dimir Midrange",
        "place": 24
      },
      {
        "player": "Martin_Dominguez",
        "deck": "Jeskai Control",
        "place": 25
      },
      {
        "player": "peter780108",
        "deck": "Azorius Control",
        "place": 26
      },
      {
        "player": "MixolydianMagus",
        "deck": "UB",
        "place": 27
      },
      {
        "player": "TheManLand",
        "deck": "Izzet Lessons",
        "place": 28
      },
      {
        "player": "elBB",
        "deck": "Esper Self-Bounce",
        "place": 29
      },
      {
        "player": "marcoshadow",
        "deck": "Izzet Lessons",
        "place": 30
      },
      {
        "player": "Aardos",
        "deck": "Bant Airbending Combo",
        "place": 31
      },
      {
        "player": "Predrag133",
        "deck": "Lifegain",
        "place": 32
      }
    ]
  }
];
