// Auto-generated by scrape.py — do not edit manually
// Last updated: 2026-03-24 16:50 UTC
const LCQ_DATA = [
  {
    "date": "2026-03-24",
    "format": "vintage",
    "event": "Vintage Last Chance 2026-03-24",
    "url": "https://www.mtggoldfish.com/tournament/62604",
    "players": 32,
    "decklists": [
      {
        "player": "Shuichi_Saito",
        "deck": "Raker Shops",
        "place": 1,
        "deck_url": "https://www.mtggoldfish.com/deck/7698711"
      },
      {
        "player": "TrueHero",
        "deck": "Azorius Initiative",
        "place": 2,
        "deck_url": "https://www.mtggoldfish.com/deck/7698702"
      },
      {
        "player": "416FrowningTable",
        "deck": "Lurrus Breach",
        "place": 3,
        "deck_url": "https://www.mtggoldfish.com/deck/7698701"
      },
      {
        "player": "Montolio",
        "deck": "Sphere Shops",
        "place": 4,
        "deck_url": "https://www.mtggoldfish.com/deck/7698682"
      },
      {
        "player": "unstar",
        "deck": "Esper Lurrus Control",
        "place": 5,
        "deck_url": "https://www.mtggoldfish.com/deck/7698709"
      },
      {
        "player": "bless_von",
        "deck": "Lurrus PO",
        "place": 6,
        "deck_url": "https://www.mtggoldfish.com/deck/7698699"
      },
      {
        "player": "moon11",
        "deck": "Sphere Shops",
        "place": 7,
        "deck_url": "https://www.mtggoldfish.com/deck/7698691"
      },
      {
        "player": "kytk321",
        "deck": "Raker Shops",
        "place": 8,
        "deck_url": "https://www.mtggoldfish.com/deck/7698700"
      },
      {
        "player": "_Shatun_",
        "deck": "Sphere Shops",
        "place": 9,
        "deck_url": "https://www.mtggoldfish.com/deck/7698688"
      },
      {
        "player": "Tsubasa_Cat",
        "deck": "Lurrus PO",
        "place": 10,
        "deck_url": "https://www.mtggoldfish.com/deck/7698698"
      },
      {
        "player": "CrazyMorango",
        "deck": "Lurrus Breach",
        "place": 11,
        "deck_url": "https://www.mtggoldfish.com/deck/7698708"
      },
      {
        "player": "HazuhiroNakamura",
        "deck": "Raker Shops",
        "place": 12,
        "deck_url": "https://www.mtggoldfish.com/deck/7698696"
      },
      {
        "player": "MissTrigger",
        "deck": "Sphere Shops",
        "place": 13,
        "deck_url": "https://www.mtggoldfish.com/deck/7698690"
      },
      {
        "player": "LucasG1ggs",
        "deck": "Oath of Druids",
        "place": 14,
        "deck_url": "https://www.mtggoldfish.com/deck/7698687"
      },
      {
        "player": "mei0024",
        "deck": "U",
        "place": 15,
        "deck_url": "https://www.mtggoldfish.com/deck/7698697"
      },
      {
        "player": "Cazuza",
        "deck": "Esper Lurrus Control",
        "place": 16,
        "deck_url": "https://www.mtggoldfish.com/deck/7698707"
      },
      {
        "player": "i_b_TRUE",
        "deck": "Dimir Lurrus Control",
        "place": 17,
        "deck_url": "https://www.mtggoldfish.com/deck/7698686"
      },
      {
        "player": "Gregoriusil",
        "deck": "Esper Lurrus Control",
        "place": 18,
        "deck_url": "https://www.mtggoldfish.com/deck/7698706"
      },
      {
        "player": "NMT_Sco94",
        "deck": "Sphere Shops",
        "place": 19,
        "deck_url": "https://www.mtggoldfish.com/deck/7698704"
      },
      {
        "player": "kobayui",
        "deck": "Dimir Lurrus Control",
        "place": 20,
        "deck_url": "https://www.mtggoldfish.com/deck/7698693"
      },
      {
        "player": "inspiratiekever",
        "deck": "Lurrus PO",
        "place": 21,
        "deck_url": "https://www.mtggoldfish.com/deck/7698712"
      },
      {
        "player": "blackdecks99",
        "deck": "Dredge",
        "place": 22,
        "deck_url": "https://www.mtggoldfish.com/deck/7698694"
      },
      {
        "player": "MyPotatoes",
        "deck": "WUG",
        "place": 23,
        "deck_url": "https://www.mtggoldfish.com/deck/7698710"
      },
      {
        "player": "bomberboss",
        "deck": "Mono-White Initiative",
        "place": 24,
        "deck_url": "https://www.mtggoldfish.com/deck/7698695"
      },
      {
        "player": "NathanLipetz",
        "deck": "Jewel Shops",
        "place": 25,
        "deck_url": "https://www.mtggoldfish.com/deck/7698703"
      },
      {
        "player": "TristanJWL",
        "deck": "Esper Lurrus Control",
        "place": 26,
        "deck_url": "https://www.mtggoldfish.com/deck/7698683"
      },
      {
        "player": "ziofrancone",
        "deck": "Esper Lurrus Control",
        "place": 27,
        "deck_url": "https://www.mtggoldfish.com/deck/7698705"
      },
      {
        "player": "desolutionist",
        "deck": "Lurrus Breach",
        "place": 28,
        "deck_url": "https://www.mtggoldfish.com/deck/7698684"
      },
      {
        "player": "IamActuallyLvL1",
        "deck": "Lurrus PO",
        "place": 29,
        "deck_url": "https://www.mtggoldfish.com/deck/7698692"
      },
      {
        "player": "slaxx",
        "deck": "Esper Lurrus Control",
        "place": 30,
        "deck_url": "https://www.mtggoldfish.com/deck/7698685"
      },
      {
        "player": "ecobaronen",
        "deck": "Dimir Lurrus Control",
        "place": 31,
        "deck_url": "https://www.mtggoldfish.com/deck/7698689"
      },
      {
        "player": "PainterMTG",
        "deck": "Sphere Shops",
        "place": 32,
        "deck_url": "https://www.mtggoldfish.com/deck/7698713"
      }
    ]
  },
  {
    "date": "2026-03-24",
    "format": "standard",
    "event": "Standard Last Chance 2026-03-24",
    "url": "https://www.mtggoldfish.com/tournament/62602",
    "players": 32,
    "decklists": [
      {
        "player": "filpin",
        "deck": "Izzet Prowess",
        "place": 1,
        "deck_url": "https://www.mtggoldfish.com/deck/7698454"
      },
      {
        "player": "Nadu",
        "deck": "Izzet Prowess",
        "place": 2,
        "deck_url": "https://www.mtggoldfish.com/deck/7698456"
      },
      {
        "player": "Univerce",
        "deck": "4c Ouroboroid",
        "place": 3,
        "deck_url": "https://www.mtggoldfish.com/deck/7698446"
      },
      {
        "player": "Boucha",
        "deck": "Mono-White Momo",
        "place": 4,
        "deck_url": "https://www.mtggoldfish.com/deck/7698431"
      },
      {
        "player": "Reiam",
        "deck": "Temur Kona",
        "place": 5,
        "deck_url": "https://www.mtggoldfish.com/deck/7698451"
      },
      {
        "player": "dawido",
        "deck": "Izzet Lessons",
        "place": 6,
        "deck_url": "https://www.mtggoldfish.com/deck/7698458"
      },
      {
        "player": "il_matagatto",
        "deck": "Mono-White Momo",
        "place": 7,
        "deck_url": "https://www.mtggoldfish.com/deck/7698438"
      },
      {
        "player": "pizzangry",
        "deck": "Mono-Green Landfall",
        "place": 8,
        "deck_url": "https://www.mtggoldfish.com/deck/7698450"
      },
      {
        "player": "groot02",
        "deck": "Izzet Lessons",
        "place": 9,
        "deck_url": "https://www.mtggoldfish.com/deck/7698455"
      },
      {
        "player": "RezerDeDog",
        "deck": "Izzet Spellementals",
        "place": 10,
        "deck_url": "https://www.mtggoldfish.com/deck/7698453"
      },
      {
        "player": "surgetemelo",
        "deck": "Izzet Lessons",
        "place": 11,
        "deck_url": "https://www.mtggoldfish.com/deck/7698459"
      },
      {
        "player": "Roquefort",
        "deck": "Mono-Green Landfall",
        "place": 12,
        "deck_url": "https://www.mtggoldfish.com/deck/7698433"
      },
      {
        "player": "kbol_",
        "deck": "Mono-Green Landfall",
        "place": 13,
        "deck_url": "https://www.mtggoldfish.com/deck/7698435"
      },
      {
        "player": "Capriccioso",
        "deck": "WUG",
        "place": 14,
        "deck_url": "https://www.mtggoldfish.com/deck/7698429"
      },
      {
        "player": "Ebnus",
        "deck": "Izzet Prowess",
        "place": 15,
        "deck_url": "https://www.mtggoldfish.com/deck/7698437"
      },
      {
        "player": "EthanBird",
        "deck": "Izzet Prowess",
        "place": 16,
        "deck_url": "https://www.mtggoldfish.com/deck/7698442"
      },
      {
        "player": "mei0024",
        "deck": "Mono-Green Landfall",
        "place": 17,
        "deck_url": "https://www.mtggoldfish.com/deck/7698439"
      },
      {
        "player": "Thalai",
        "deck": "Mono-Green Landfall",
        "place": 18,
        "deck_url": "https://www.mtggoldfish.com/deck/7698428"
      },
      {
        "player": "rampantoaf",
        "deck": "Allies",
        "place": 19,
        "deck_url": "https://www.mtggoldfish.com/deck/7698445"
      },
      {
        "player": "O_danielakos",
        "deck": "Dimir Midrange",
        "place": 20,
        "deck_url": "https://www.mtggoldfish.com/deck/7698434"
      },
      {
        "player": "mariogomes097",
        "deck": "WUBG",
        "place": 21,
        "deck_url": "https://www.mtggoldfish.com/deck/7698441"
      },
      {
        "player": "VictorEsquici",
        "deck": "Izzet Spellementals",
        "place": 22,
        "deck_url": "https://www.mtggoldfish.com/deck/7698449"
      },
      {
        "player": "elBB",
        "deck": "Izzet Spellementals",
        "place": 23,
        "deck_url": "https://www.mtggoldfish.com/deck/7698448"
      },
      {
        "player": "BoreiMTG",
        "deck": "Mono-Green Landfall",
        "place": 24,
        "deck_url": "https://www.mtggoldfish.com/deck/7698452"
      },
      {
        "player": "brandi96",
        "deck": "Izzet Lessons",
        "place": 25,
        "deck_url": "https://www.mtggoldfish.com/deck/7698436"
      },
      {
        "player": "CrazyMorango",
        "deck": "Izzet Lessons",
        "place": 26,
        "deck_url": "https://www.mtggoldfish.com/deck/7698447"
      },
      {
        "player": "KadettiKersantti",
        "deck": "Izzet Lessons",
        "place": 27,
        "deck_url": "https://www.mtggoldfish.com/deck/7698457"
      },
      {
        "player": "Azja",
        "deck": "Izzet Prowess",
        "place": 28,
        "deck_url": "https://www.mtggoldfish.com/deck/7698444"
      },
      {
        "player": "LucasG1ggs",
        "deck": "WR",
        "place": 29,
        "deck_url": "https://www.mtggoldfish.com/deck/7698430"
      },
      {
        "player": "Ale_Mtg",
        "deck": "Izzet Prowess",
        "place": 30,
        "deck_url": "https://www.mtggoldfish.com/deck/7698443"
      },
      {
        "player": "quinniac",
        "deck": "Mono-Red Aggro",
        "place": 31,
        "deck_url": "https://www.mtggoldfish.com/deck/7698440"
      },
      {
        "player": "Daniluengos14",
        "deck": "Izzet Spellementals",
        "place": 32,
        "deck_url": "https://www.mtggoldfish.com/deck/7698432"
      }
    ]
  },
  {
    "date": "2026-03-24",
    "format": "legacy",
    "event": "Legacy Last Chance 2026-03-24",
    "url": "https://www.mtggoldfish.com/tournament/62601",
    "players": 32,
    "decklists": [
      {
        "player": "Aced5",
        "deck": "Dimir Tempo",
        "place": 1,
        "deck_url": "https://www.mtggoldfish.com/deck/7698261"
      },
      {
        "player": "WataugaCJ",
        "deck": "Oops! All Spells",
        "place": 2,
        "deck_url": "https://www.mtggoldfish.com/deck/7698278"
      },
      {
        "player": "zNoodz",
        "deck": "Jeskai Stoneblade",
        "place": 3,
        "deck_url": "https://www.mtggoldfish.com/deck/7698275"
      },
      {
        "player": "wongdeck",
        "deck": "Lands",
        "place": 4,
        "deck_url": "https://www.mtggoldfish.com/deck/7698277"
      },
      {
        "player": "Univerce",
        "deck": "Colorless",
        "place": 5,
        "deck_url": "https://www.mtggoldfish.com/deck/7698285"
      },
      {
        "player": "GigaChadSigmaMale",
        "deck": "Dimir Tempo",
        "place": 6,
        "deck_url": "https://www.mtggoldfish.com/deck/7698289"
      },
      {
        "player": "derlumberzack",
        "deck": "Sneak and Show",
        "place": 7,
        "deck_url": "https://www.mtggoldfish.com/deck/7698268"
      },
      {
        "player": "minyafriend",
        "deck": "Dimir Tempo",
        "place": 8,
        "deck_url": "https://www.mtggoldfish.com/deck/7698263"
      },
      {
        "player": "bless_von",
        "deck": "Colorless",
        "place": 9,
        "deck_url": "https://www.mtggoldfish.com/deck/7698274"
      },
      {
        "player": "Lord_Beerus",
        "deck": "Dimir Tempo",
        "place": 10,
        "deck_url": "https://www.mtggoldfish.com/deck/7698273"
      },
      {
        "player": "Cachorrowo",
        "deck": "Oops! All Spells",
        "place": 11,
        "deck_url": "https://www.mtggoldfish.com/deck/7698280"
      },
      {
        "player": "___panicking",
        "deck": "Lands",
        "place": 12,
        "deck_url": "https://www.mtggoldfish.com/deck/7698287"
      },
      {
        "player": "Shuichi_Saito",
        "deck": "Colorless",
        "place": 13,
        "deck_url": "https://www.mtggoldfish.com/deck/7698290"
      },
      {
        "player": "Stanshine",
        "deck": "Affinity Stompy",
        "place": 14,
        "deck_url": "https://www.mtggoldfish.com/deck/7698265"
      },
      {
        "player": "bcs8995",
        "deck": "Ocelot Pride Midrange",
        "place": 15,
        "deck_url": "https://www.mtggoldfish.com/deck/7698270"
      },
      {
        "player": "Eureka22422",
        "deck": "Doomsday",
        "place": 16,
        "deck_url": "https://www.mtggoldfish.com/deck/7698269"
      },
      {
        "player": "lilianna1989",
        "deck": "Colorless",
        "place": 17,
        "deck_url": "https://www.mtggoldfish.com/deck/7698282"
      },
      {
        "player": "Venom1",
        "deck": "Ocelot Pride Midrange",
        "place": 18,
        "deck_url": "https://www.mtggoldfish.com/deck/7698267"
      },
      {
        "player": "CliffBoyardee",
        "deck": "Dimir Tempo",
        "place": 19,
        "deck_url": "https://www.mtggoldfish.com/deck/7698284"
      },
      {
        "player": "Sommertroll",
        "deck": "Affinity Stompy",
        "place": 20,
        "deck_url": "https://www.mtggoldfish.com/deck/7698281"
      },
      {
        "player": "fingers1991",
        "deck": "Dimir Tempo",
        "place": 21,
        "deck_url": "https://www.mtggoldfish.com/deck/7698262"
      },
      {
        "player": "duke12",
        "deck": "Colorless",
        "place": 22,
        "deck_url": "https://www.mtggoldfish.com/deck/7698260"
      },
      {
        "player": "Roodslay",
        "deck": "UBG",
        "place": 23,
        "deck_url": "https://www.mtggoldfish.com/deck/7698279"
      },
      {
        "player": "O_danielakos",
        "deck": "Izzet Delver",
        "place": 24,
        "deck_url": "https://www.mtggoldfish.com/deck/7698266"
      },
      {
        "player": "kozz27",
        "deck": "Naya Initiative",
        "place": 25,
        "deck_url": "https://www.mtggoldfish.com/deck/7698271"
      },
      {
        "player": "LukeBrandes",
        "deck": "WU",
        "place": 26,
        "deck_url": "https://www.mtggoldfish.com/deck/7698286"
      },
      {
        "player": "__Neptune__",
        "deck": "Doomsday",
        "place": 27,
        "deck_url": "https://www.mtggoldfish.com/deck/7698291"
      },
      {
        "player": "TentacleFan",
        "deck": "Colorless",
        "place": 28,
        "deck_url": "https://www.mtggoldfish.com/deck/7698288"
      },
      {
        "player": "RPSbonjwa",
        "deck": "Affinity Stompy",
        "place": 29,
        "deck_url": "https://www.mtggoldfish.com/deck/7698283"
      },
      {
        "player": "usea",
        "deck": "Death&#39;s Shadow",
        "place": 30,
        "deck_url": "https://www.mtggoldfish.com/deck/7698276"
      },
      {
        "player": "C_S_W____",
        "deck": "Beanstalk Control (Non-Yorion)",
        "place": 31,
        "deck_url": "https://www.mtggoldfish.com/deck/7698264"
      },
      {
        "player": "oOMegaGenesis",
        "deck": "W",
        "place": 32,
        "deck_url": "https://www.mtggoldfish.com/deck/7698272"
      }
    ]
  },
  {
    "date": "2026-03-23",
    "format": "vintage",
    "event": "Vintage Last Chance 2026-03-23 (1)",
    "url": "https://www.mtggoldfish.com/tournament/62609",
    "players": 32,
    "decklists": [
      {
        "player": "Miharu_Fuyumiya",
        "deck": "Lurrus PO",
        "place": 1,
        "deck_url": "https://www.mtggoldfish.com/deck/7698865"
      },
      {
        "player": "scalo94",
        "deck": "Lurrus PO",
        "place": 2,
        "deck_url": "https://www.mtggoldfish.com/deck/7698851"
      },
      {
        "player": "IamActuallyLvL1",
        "deck": "Sphere Shops",
        "place": 3,
        "deck_url": "https://www.mtggoldfish.com/deck/7698859"
      },
      {
        "player": "Anonymous",
        "deck": "Sphere Shops",
        "place": 4,
        "deck_url": "https://www.mtggoldfish.com/deck/7698861"
      },
      {
        "player": "AFX",
        "deck": "Raker Shops",
        "place": 5,
        "deck_url": "https://www.mtggoldfish.com/deck/7698855"
      },
      {
        "player": "NathanOfTheGiltLeaf",
        "deck": "Esper Lurrus Control",
        "place": 6,
        "deck_url": "https://www.mtggoldfish.com/deck/7698869"
      },
      {
        "player": "_Shatun_",
        "deck": "Sphere Shops",
        "place": 7,
        "deck_url": "https://www.mtggoldfish.com/deck/7698853"
      },
      {
        "player": "4FunNoWin",
        "deck": "Lurrus PO",
        "place": 8,
        "deck_url": "https://www.mtggoldfish.com/deck/7698873"
      },
      {
        "player": "Tsubasa_Cat",
        "deck": "Dimir Lurrus Control",
        "place": 9,
        "deck_url": "https://www.mtggoldfish.com/deck/7698862"
      },
      {
        "player": "oskiyaa",
        "deck": "Dredge",
        "place": 10,
        "deck_url": "https://www.mtggoldfish.com/deck/7698856"
      },
      {
        "player": "crK",
        "deck": "Sphere Shops",
        "place": 11,
        "deck_url": "https://www.mtggoldfish.com/deck/7698852"
      },
      {
        "player": "HugoVenda",
        "deck": "Mono-White Initiative",
        "place": 12,
        "deck_url": "https://www.mtggoldfish.com/deck/7698848"
      },
      {
        "player": "duke12",
        "deck": "Lurrus PO",
        "place": 13,
        "deck_url": "https://www.mtggoldfish.com/deck/7698843"
      },
      {
        "player": "blub_blub",
        "deck": "Lurrus Breach",
        "place": 14,
        "deck_url": "https://www.mtggoldfish.com/deck/7698874"
      },
      {
        "player": "magiclaszlo",
        "deck": "Sphere Shops",
        "place": 15,
        "deck_url": "https://www.mtggoldfish.com/deck/7698844"
      },
      {
        "player": "sebastianpozzo",
        "deck": "Dredge",
        "place": 16,
        "deck_url": "https://www.mtggoldfish.com/deck/7698845"
      },
      {
        "player": "_Batutinha_",
        "deck": "Esper Lurrus Control",
        "place": 17,
        "deck_url": "https://www.mtggoldfish.com/deck/7698846"
      },
      {
        "player": "MJ_23",
        "deck": "Mono-White Initiative",
        "place": 18,
        "deck_url": "https://www.mtggoldfish.com/deck/7698850"
      },
      {
        "player": "xfile",
        "deck": "Lurrus PO",
        "place": 19,
        "deck_url": "https://www.mtggoldfish.com/deck/7698864"
      },
      {
        "player": "inspiratiekever",
        "deck": "Lurrus PO",
        "place": 20,
        "deck_url": "https://www.mtggoldfish.com/deck/7698872"
      },
      {
        "player": "chanel-santini",
        "deck": "Doomsday",
        "place": 21,
        "deck_url": "https://www.mtggoldfish.com/deck/7698870"
      },
      {
        "player": "boytriton",
        "deck": "Lurrus Breach",
        "place": 22,
        "deck_url": "https://www.mtggoldfish.com/deck/7698867"
      },
      {
        "player": "thestudygroup",
        "deck": "Esper Lurrus Control",
        "place": 23,
        "deck_url": "https://www.mtggoldfish.com/deck/7698857"
      },
      {
        "player": "mortr3d",
        "deck": "Raker Shops",
        "place": 24,
        "deck_url": "https://www.mtggoldfish.com/deck/7698847"
      },
      {
        "player": "Frejat",
        "deck": "Esper Lurrus Control",
        "place": 25,
        "deck_url": "https://www.mtggoldfish.com/deck/7698858"
      },
      {
        "player": "LucasG1ggs",
        "deck": "Sphere Shops",
        "place": 26,
        "deck_url": "https://www.mtggoldfish.com/deck/7698849"
      },
      {
        "player": "ecobaronen",
        "deck": "Dimir Lurrus Control",
        "place": 27,
        "deck_url": "https://www.mtggoldfish.com/deck/7698854"
      },
      {
        "player": "416FrowningTable",
        "deck": "Lurrus Breach",
        "place": 28,
        "deck_url": "https://www.mtggoldfish.com/deck/7698863"
      },
      {
        "player": "Milkshake_",
        "deck": "Sphere Shops",
        "place": 29,
        "deck_url": "https://www.mtggoldfish.com/deck/7698871"
      },
      {
        "player": "Univerce",
        "deck": "Doomsday",
        "place": 30,
        "deck_url": "https://www.mtggoldfish.com/deck/7698868"
      },
      {
        "player": "blackdecks99",
        "deck": "Dredge",
        "place": 31,
        "deck_url": "https://www.mtggoldfish.com/deck/7698860"
      },
      {
        "player": "-Nausea-",
        "deck": "Jewel Shops",
        "place": 32,
        "deck_url": "https://www.mtggoldfish.com/deck/7698866"
      }
    ]
  },
  {
    "date": "2026-03-23",
    "format": "modern",
    "event": "Modern Last Chance 2026-03-23 (1)",
    "url": "https://www.mtggoldfish.com/tournament/62598",
    "players": 32,
    "decklists": [
      {
        "player": "NukaCola",
        "deck": "Neobrand",
        "place": 1,
        "deck_url": "https://www.mtggoldfish.com/deck/7698043"
      },
      {
        "player": "McWinSauce",
        "deck": "Jeskai Blink",
        "place": 2,
        "deck_url": "https://www.mtggoldfish.com/deck/7698037"
      },
      {
        "player": "Daking3603",
        "deck": "Boros Energy",
        "place": 3,
        "deck_url": "https://www.mtggoldfish.com/deck/7698045"
      },
      {
        "player": "levunga21",
        "deck": "WU",
        "place": 4,
        "deck_url": "https://www.mtggoldfish.com/deck/7698035"
      },
      {
        "player": "bless_von",
        "deck": "Boros Energy",
        "place": 5,
        "deck_url": "https://www.mtggoldfish.com/deck/7698049"
      },
      {
        "player": "Univerce",
        "deck": "Amulet Titan",
        "place": 6,
        "deck_url": "https://www.mtggoldfish.com/deck/7698053"
      },
      {
        "player": "Kollslaw",
        "deck": "Amulet Titan",
        "place": 7,
        "deck_url": "https://www.mtggoldfish.com/deck/7698061"
      },
      {
        "player": "scipios",
        "deck": "Amulet Titan",
        "place": 8,
        "deck_url": "https://www.mtggoldfish.com/deck/7698050"
      },
      {
        "player": "moon11",
        "deck": "Domain Zoo",
        "place": 9,
        "deck_url": "https://www.mtggoldfish.com/deck/7698041"
      },
      {
        "player": "moreno13",
        "deck": "Affinity",
        "place": 10,
        "deck_url": "https://www.mtggoldfish.com/deck/7698058"
      },
      {
        "player": "quinniac",
        "deck": "Belcher",
        "place": 11,
        "deck_url": "https://www.mtggoldfish.com/deck/7698048"
      },
      {
        "player": "rastaf",
        "deck": "Boros Energy",
        "place": 12,
        "deck_url": "https://www.mtggoldfish.com/deck/7698033"
      },
      {
        "player": "DjentReznor",
        "deck": "Domain Zoo",
        "place": 13,
        "deck_url": "https://www.mtggoldfish.com/deck/7698038"
      },
      {
        "player": "duke12",
        "deck": "Goryo&#39;s Vengeance",
        "place": 14,
        "deck_url": "https://www.mtggoldfish.com/deck/7698032"
      },
      {
        "player": "Harry1232",
        "deck": "Goryo&#39;s Vengeance",
        "place": 15,
        "deck_url": "https://www.mtggoldfish.com/deck/7698042"
      },
      {
        "player": "GothMuse",
        "deck": "Boros Energy",
        "place": 16,
        "deck_url": "https://www.mtggoldfish.com/deck/7698059"
      },
      {
        "player": "azax",
        "deck": "Ruby Storm",
        "place": 17,
        "deck_url": "https://www.mtggoldfish.com/deck/7698046"
      },
      {
        "player": "Venom1",
        "deck": "Jeskai Blink",
        "place": 18,
        "deck_url": "https://www.mtggoldfish.com/deck/7698039"
      },
      {
        "player": "sebastianpozzo",
        "deck": "Affinity",
        "place": 19,
        "deck_url": "https://www.mtggoldfish.com/deck/7698034"
      },
      {
        "player": "EnderW",
        "deck": "Dimir Tezzerator",
        "place": 20,
        "deck_url": "https://www.mtggoldfish.com/deck/7698054"
      },
      {
        "player": "NJ5030",
        "deck": "Boros Energy",
        "place": 21,
        "deck_url": "https://www.mtggoldfish.com/deck/7698056"
      },
      {
        "player": "MeninoNey",
        "deck": "Living End",
        "place": 22,
        "deck_url": "https://www.mtggoldfish.com/deck/7698052"
      },
      {
        "player": "MendezCL",
        "deck": "Boros Energy",
        "place": 23,
        "deck_url": "https://www.mtggoldfish.com/deck/7698060"
      },
      {
        "player": "sioutis_kk",
        "deck": "Affinity",
        "place": 24,
        "deck_url": "https://www.mtggoldfish.com/deck/7698063"
      },
      {
        "player": "ShadowTitan1",
        "deck": "Domain Zoo",
        "place": 25,
        "deck_url": "https://www.mtggoldfish.com/deck/7698044"
      },
      {
        "player": "SoulStrong",
        "deck": "Goryo&#39;s Vengeance",
        "place": 26,
        "deck_url": "https://www.mtggoldfish.com/deck/7698040"
      },
      {
        "player": "ajoloT",
        "deck": "Amulet Titan",
        "place": 27,
        "deck_url": "https://www.mtggoldfish.com/deck/7698051"
      },
      {
        "player": "Xsper",
        "deck": "Temur Prowess",
        "place": 28,
        "deck_url": "https://www.mtggoldfish.com/deck/7698057"
      },
      {
        "player": "LucasG1ggs",
        "deck": "Affinity",
        "place": 29,
        "deck_url": "https://www.mtggoldfish.com/deck/7698036"
      },
      {
        "player": "MtgoUser031832121",
        "deck": "Boros Energy",
        "place": 30,
        "deck_url": "https://www.mtggoldfish.com/deck/7698062"
      },
      {
        "player": "MohammedbinSalman",
        "deck": "Jeskai Blink",
        "place": 31,
        "deck_url": "https://www.mtggoldfish.com/deck/7698055"
      },
      {
        "player": "lillo6",
        "deck": "Boros Energy",
        "place": 32,
        "deck_url": "https://www.mtggoldfish.com/deck/7698047"
      }
    ]
  },
  {
    "date": "2026-03-23",
    "format": "standard",
    "event": "Standard Last Chance 2026-03-23 (1)",
    "url": "https://www.mtggoldfish.com/tournament/62585",
    "players": 32,
    "decklists": [
      {
        "player": "kanister",
        "deck": "Izzet Lessons",
        "place": 1,
        "deck_url": "https://www.mtggoldfish.com/deck/7697499"
      },
      {
        "player": "Salvatto",
        "deck": "Mono-Green Landfall",
        "place": 2,
        "deck_url": "https://www.mtggoldfish.com/deck/7697493"
      },
      {
        "player": "SanPop",
        "deck": "Izzet Prowess",
        "place": 3,
        "deck_url": "https://www.mtggoldfish.com/deck/7697504"
      },
      {
        "player": "RCMerriam",
        "deck": "Izzet Prowess",
        "place": 4,
        "deck_url": "https://www.mtggoldfish.com/deck/7697494"
      },
      {
        "player": "willjetz1323",
        "deck": "Mono-Green Landfall",
        "place": 5,
        "deck_url": "https://www.mtggoldfish.com/deck/7697495"
      },
      {
        "player": "RespectTheCat",
        "deck": "5c Elementals",
        "place": 6,
        "deck_url": "https://www.mtggoldfish.com/deck/7697510"
      },
      {
        "player": "Valimoth",
        "deck": "Izzet Spellementals",
        "place": 7,
        "deck_url": "https://www.mtggoldfish.com/deck/7697514"
      },
      {
        "player": "MKC",
        "deck": "Mono-Green Landfall",
        "place": 8,
        "deck_url": "https://www.mtggoldfish.com/deck/7697491"
      },
      {
        "player": "surgetemelo",
        "deck": "Dimir Excruciator",
        "place": 9,
        "deck_url": "https://www.mtggoldfish.com/deck/7697521"
      },
      {
        "player": "_Tia93_",
        "deck": "Izzet Lessons",
        "place": 10,
        "deck_url": "https://www.mtggoldfish.com/deck/7697500"
      },
      {
        "player": "ashame",
        "deck": "Izzet Prowess",
        "place": 11,
        "deck_url": "https://www.mtggoldfish.com/deck/7697509"
      },
      {
        "player": "Azja",
        "deck": "Izzet Prowess",
        "place": 12,
        "deck_url": "https://www.mtggoldfish.com/deck/7697508"
      },
      {
        "player": "Ale_Mtg",
        "deck": "Bant Ouroboroid",
        "place": 13,
        "deck_url": "https://www.mtggoldfish.com/deck/7697506"
      },
      {
        "player": "NJ5030",
        "deck": "Izzet Prowess",
        "place": 14,
        "deck_url": "https://www.mtggoldfish.com/deck/7697516"
      },
      {
        "player": "Xenowan",
        "deck": "4c Ouroboroid",
        "place": 15,
        "deck_url": "https://www.mtggoldfish.com/deck/7697503"
      },
      {
        "player": "elBB",
        "deck": "Izzet Prowess",
        "place": 16,
        "deck_url": "https://www.mtggoldfish.com/deck/7697515"
      },
      {
        "player": "CrazyMorango",
        "deck": "Izzet Lessons",
        "place": 17,
        "deck_url": "https://www.mtggoldfish.com/deck/7697513"
      },
      {
        "player": "terlollo04",
        "deck": "Izzet Prowess",
        "place": 18,
        "deck_url": "https://www.mtggoldfish.com/deck/7697502"
      },
      {
        "player": "Thief_Of_Crowns",
        "deck": "BG",
        "place": 19,
        "deck_url": "https://www.mtggoldfish.com/deck/7697517"
      },
      {
        "player": "Terminus0",
        "deck": "Izzet Lessons",
        "place": 20,
        "deck_url": "https://www.mtggoldfish.com/deck/7697501"
      },
      {
        "player": "Mldyss",
        "deck": "Izzet Spellementals",
        "place": 21,
        "deck_url": "https://www.mtggoldfish.com/deck/7697511"
      },
      {
        "player": "sebastianpozzo",
        "deck": "Bant Ouroboroid",
        "place": 22,
        "deck_url": "https://www.mtggoldfish.com/deck/7697490"
      },
      {
        "player": "Kritik",
        "deck": "4c Control",
        "place": 23,
        "deck_url": "https://www.mtggoldfish.com/deck/7697507"
      },
      {
        "player": "BERNASTORRES",
        "deck": "Izzet Spellementals",
        "place": 24,
        "deck_url": "https://www.mtggoldfish.com/deck/7697496"
      },
      {
        "player": "MultiformatSuperstar",
        "deck": "Izzet Spellementals",
        "place": 25,
        "deck_url": "https://www.mtggoldfish.com/deck/7697505"
      },
      {
        "player": "LucasG1ggs",
        "deck": "Mono-Green Landfall",
        "place": 26,
        "deck_url": "https://www.mtggoldfish.com/deck/7697492"
      },
      {
        "player": "MacIsaac",
        "deck": "Temur Prowess",
        "place": 27,
        "deck_url": "https://www.mtggoldfish.com/deck/7697519"
      },
      {
        "player": "SpockVidaLoka",
        "deck": "Bant Ouroboroid",
        "place": 28,
        "deck_url": "https://www.mtggoldfish.com/deck/7697512"
      },
      {
        "player": "makaaaa",
        "deck": "Izzet Prowess",
        "place": 29,
        "deck_url": "https://www.mtggoldfish.com/deck/7697518"
      },
      {
        "player": "Venom1",
        "deck": "Mono-Green Landfall",
        "place": 30,
        "deck_url": "https://www.mtggoldfish.com/deck/7697497"
      },
      {
        "player": "groot02",
        "deck": "Izzet Lessons",
        "place": 31,
        "deck_url": "https://www.mtggoldfish.com/deck/7697520"
      },
      {
        "player": "wolf2222",
        "deck": "Izzet Spellementals",
        "place": 32,
        "deck_url": "https://www.mtggoldfish.com/deck/7697498"
      }
    ]
  },
  {
    "date": "2026-03-23",
    "format": "standard",
    "event": "Standard Last Chance 2026-03-23 (1)",
    "url": "https://www.mtggoldfish.com/tournament/62577",
    "players": 32,
    "decklists": [
      {
        "player": "rastaf",
        "deck": "Mono-Green Landfall",
        "place": 1,
        "deck_url": "https://www.mtggoldfish.com/deck/7697037"
      },
      {
        "player": "Capriccioso",
        "deck": "Azorius Momo",
        "place": 2,
        "deck_url": "https://www.mtggoldfish.com/deck/7697041"
      },
      {
        "player": "eggybenny",
        "deck": "Izzet Prowess",
        "place": 3,
        "deck_url": "https://www.mtggoldfish.com/deck/7697052"
      },
      {
        "player": "_Babbuja_",
        "deck": "Dimir Excruciator",
        "place": 4,
        "deck_url": "https://www.mtggoldfish.com/deck/7697066"
      },
      {
        "player": "LucasG1ggs",
        "deck": "Mono-Green Landfall",
        "place": 5,
        "deck_url": "https://www.mtggoldfish.com/deck/7697043"
      },
      {
        "player": "GTX120",
        "deck": "Mono-White Momo",
        "place": 6,
        "deck_url": "https://www.mtggoldfish.com/deck/7697049"
      },
      {
        "player": "Chichichi",
        "deck": "Izzet Spellementals",
        "place": 7,
        "deck_url": "https://www.mtggoldfish.com/deck/7697055"
      },
      {
        "player": "ashame",
        "deck": "Izzet Prowess",
        "place": 8,
        "deck_url": "https://www.mtggoldfish.com/deck/7697054"
      },
      {
        "player": "indianpancake",
        "deck": "Mono-Green Landfall",
        "place": 9,
        "deck_url": "https://www.mtggoldfish.com/deck/7697047"
      },
      {
        "player": "NJ5030",
        "deck": "Izzet Prowess",
        "place": 10,
        "deck_url": "https://www.mtggoldfish.com/deck/7697062"
      },
      {
        "player": "VictorEsquici",
        "deck": "Izzet Spellementals",
        "place": 11,
        "deck_url": "https://www.mtggoldfish.com/deck/7697061"
      },
      {
        "player": "Salvatto",
        "deck": "Bant Ouroboroid",
        "place": 12,
        "deck_url": "https://www.mtggoldfish.com/deck/7697045"
      },
      {
        "player": "CrazyMorango",
        "deck": "Izzet Lessons",
        "place": 13,
        "deck_url": "https://www.mtggoldfish.com/deck/7697057"
      },
      {
        "player": "Valimoth",
        "deck": "Izzet Spellementals",
        "place": 14,
        "deck_url": "https://www.mtggoldfish.com/deck/7697058"
      },
      {
        "player": "Skeptic2304",
        "deck": "Mono-Green Landfall",
        "place": 15,
        "deck_url": "https://www.mtggoldfish.com/deck/7697051"
      },
      {
        "player": "duke12",
        "deck": "4c Harmonizer Combo",
        "place": 16,
        "deck_url": "https://www.mtggoldfish.com/deck/7697035"
      },
      {
        "player": "Univerce",
        "deck": "4c Ouroboroid",
        "place": 17,
        "deck_url": "https://www.mtggoldfish.com/deck/7697056"
      },
      {
        "player": "Misplacedginger",
        "deck": "Izzet Lessons",
        "place": 18,
        "deck_url": "https://www.mtggoldfish.com/deck/7697042"
      },
      {
        "player": "ShadowTitan1",
        "deck": "Bant Ouroboroid",
        "place": 19,
        "deck_url": "https://www.mtggoldfish.com/deck/7697048"
      },
      {
        "player": "Merriman",
        "deck": "4c Ouroboroid",
        "place": 20,
        "deck_url": "https://www.mtggoldfish.com/deck/7697064"
      },
      {
        "player": "wolf2222",
        "deck": "Izzet Spellementals",
        "place": 21,
        "deck_url": "https://www.mtggoldfish.com/deck/7697046"
      },
      {
        "player": "Bruskk",
        "deck": "Izzet Lessons",
        "place": 22,
        "deck_url": "https://www.mtggoldfish.com/deck/7697060"
      },
      {
        "player": "Milkshake_",
        "deck": "Izzet Prowess",
        "place": 23,
        "deck_url": "https://www.mtggoldfish.com/deck/7697065"
      },
      {
        "player": "Azja",
        "deck": "Izzet Prowess",
        "place": 24,
        "deck_url": "https://www.mtggoldfish.com/deck/7697053"
      },
      {
        "player": "L1X0",
        "deck": "Mono-Green Landfall",
        "place": 25,
        "deck_url": "https://www.mtggoldfish.com/deck/7697039"
      },
      {
        "player": "Shamplade",
        "deck": "Mono-Green Landfall",
        "place": 26,
        "deck_url": "https://www.mtggoldfish.com/deck/7697059"
      },
      {
        "player": "xfile",
        "deck": "Izzet Lessons",
        "place": 27,
        "deck_url": "https://www.mtggoldfish.com/deck/7697050"
      },
      {
        "player": "Nocturne_",
        "deck": "Orzhov Midrange",
        "place": 28,
        "deck_url": "https://www.mtggoldfish.com/deck/7697044"
      },
      {
        "player": "levunga21",
        "deck": "Dimir Midrange",
        "place": 29,
        "deck_url": "https://www.mtggoldfish.com/deck/7697040"
      },
      {
        "player": "sebastianpozzo",
        "deck": "Bant Ouroboroid",
        "place": 30,
        "deck_url": "https://www.mtggoldfish.com/deck/7697038"
      },
      {
        "player": "digdude13",
        "deck": "Boros Momo",
        "place": 31,
        "deck_url": "https://www.mtggoldfish.com/deck/7697036"
      },
      {
        "player": "PedraStone",
        "deck": "Izzet Lessons",
        "place": 32,
        "deck_url": "https://www.mtggoldfish.com/deck/7697063"
      }
    ]
  },
  {
    "date": "2026-03-23",
    "format": "legacy",
    "event": "Legacy Last Chance 2026-03-23",
    "url": "https://www.mtggoldfish.com/tournament/62564",
    "players": 32,
    "decklists": [
      {
        "player": "Thalai",
        "deck": "Colorless",
        "place": 1,
        "deck_url": "https://www.mtggoldfish.com/deck/7695827"
      },
      {
        "player": "snoopy-magic",
        "deck": "Sneak and Show",
        "place": 2,
        "deck_url": "https://www.mtggoldfish.com/deck/7695838"
      },
      {
        "player": "Otazz",
        "deck": "Sultai Aluren",
        "place": 3,
        "deck_url": "https://www.mtggoldfish.com/deck/7695839"
      },
      {
        "player": "_INF_",
        "deck": "Dimir Tempo",
        "place": 4,
        "deck_url": "https://www.mtggoldfish.com/deck/7695845"
      },
      {
        "player": "choutin",
        "deck": "Oops! All Spells",
        "place": 5,
        "deck_url": "https://www.mtggoldfish.com/deck/7695856"
      },
      {
        "player": "Comrade1312",
        "deck": "Oops! All Spells",
        "place": 6,
        "deck_url": "https://www.mtggoldfish.com/deck/7695841"
      },
      {
        "player": "TheGrimLavamancer",
        "deck": "Sneak and Show",
        "place": 7,
        "deck_url": "https://www.mtggoldfish.com/deck/7695848"
      },
      {
        "player": "KurumimBagoRosa",
        "deck": "Colorless",
        "place": 8,
        "deck_url": "https://www.mtggoldfish.com/deck/7695858"
      },
      {
        "player": "kanican",
        "deck": "UBR",
        "place": 9,
        "deck_url": "https://www.mtggoldfish.com/deck/7695834"
      },
      {
        "player": "Vlalutscher",
        "deck": "The EPIC Storm",
        "place": 10,
        "deck_url": "https://www.mtggoldfish.com/deck/7695849"
      },
      {
        "player": "Xenowan",
        "deck": "Colorless",
        "place": 11,
        "deck_url": "https://www.mtggoldfish.com/deck/7695842"
      },
      {
        "player": "SlayItWithRoses",
        "deck": "Red Stompy",
        "place": 12,
        "deck_url": "https://www.mtggoldfish.com/deck/7695833"
      },
      {
        "player": "boytriton",
        "deck": "Colorless",
        "place": 13,
        "deck_url": "https://www.mtggoldfish.com/deck/7695850"
      },
      {
        "player": "JohnDoe397",
        "deck": "Death and Taxes (Yorion) - Orzhov",
        "place": 14,
        "deck_url": "https://www.mtggoldfish.com/deck/7695852"
      },
      {
        "player": "ReformedPaolo",
        "deck": "Dimir Tempo",
        "place": 15,
        "deck_url": "https://www.mtggoldfish.com/deck/7695843"
      },
      {
        "player": "manohito",
        "deck": "Oops! All Spells",
        "place": 16,
        "deck_url": "https://www.mtggoldfish.com/deck/7695851"
      },
      {
        "player": "RedArmada",
        "deck": "Dimir Reanimator",
        "place": 17,
        "deck_url": "https://www.mtggoldfish.com/deck/7695829"
      },
      {
        "player": "_Batutinha_",
        "deck": "Colorless",
        "place": 18,
        "deck_url": "https://www.mtggoldfish.com/deck/7695828"
      },
      {
        "player": "Rhysiner",
        "deck": "BG",
        "place": 19,
        "deck_url": "https://www.mtggoldfish.com/deck/7695835"
      },
      {
        "player": "discoverN",
        "deck": "Dimir Tempo",
        "place": 20,
        "deck_url": "https://www.mtggoldfish.com/deck/7695831"
      },
      {
        "player": "pepeteam",
        "deck": "Dimir Tempo",
        "place": 21,
        "deck_url": "https://www.mtggoldfish.com/deck/7695840"
      },
      {
        "player": "NathanLipetz",
        "deck": "Oops! All Spells",
        "place": 22,
        "deck_url": "https://www.mtggoldfish.com/deck/7695844"
      },
      {
        "player": "Munchlax446",
        "deck": "Dimir Tempo",
        "place": 23,
        "deck_url": "https://www.mtggoldfish.com/deck/7695854"
      },
      {
        "player": "JV_7777",
        "deck": "Dimir Tempo",
        "place": 24,
        "deck_url": "https://www.mtggoldfish.com/deck/7695836"
      },
      {
        "player": "GigaChadSigmaMale",
        "deck": "Dimir Tempo",
        "place": 25,
        "deck_url": "https://www.mtggoldfish.com/deck/7695855"
      },
      {
        "player": "zhinonono",
        "deck": "Lands",
        "place": 26,
        "deck_url": "https://www.mtggoldfish.com/deck/7695837"
      },
      {
        "player": "clan",
        "deck": "Doomsday",
        "place": 27,
        "deck_url": "https://www.mtggoldfish.com/deck/7695847"
      },
      {
        "player": "Ark4n",
        "deck": "Esper Control",
        "place": 28,
        "deck_url": "https://www.mtggoldfish.com/deck/7695832"
      },
      {
        "player": "HugoVenda",
        "deck": "Dimir Tempo",
        "place": 29,
        "deck_url": "https://www.mtggoldfish.com/deck/7695830"
      },
      {
        "player": "VenusCHN",
        "deck": "Sneak and Show",
        "place": 30,
        "deck_url": "https://www.mtggoldfish.com/deck/7695857"
      },
      {
        "player": "Roodslay",
        "deck": "UBG",
        "place": 31,
        "deck_url": "https://www.mtggoldfish.com/deck/7695846"
      },
      {
        "player": "Univerce",
        "deck": "Lands",
        "place": 32,
        "deck_url": "https://www.mtggoldfish.com/deck/7695853"
      }
    ]
  },
  {
    "date": "2026-03-23",
    "format": "modern",
    "event": "Modern Last Chance 2026-03-23",
    "url": "https://www.mtggoldfish.com/tournament/62560",
    "players": 32,
    "decklists": [
      {
        "player": "kanister",
        "deck": "Amulet Titan",
        "place": 1,
        "deck_url": "https://www.mtggoldfish.com/deck/7695668"
      },
      {
        "player": "badgods",
        "deck": "Belcher",
        "place": 2,
        "deck_url": "https://www.mtggoldfish.com/deck/7695683"
      },
      {
        "player": "surgetemelo",
        "deck": "Boros Energy",
        "place": 3,
        "deck_url": "https://www.mtggoldfish.com/deck/7695692"
      },
      {
        "player": "pizzangry",
        "deck": "Ruby Storm",
        "place": 4,
        "deck_url": "https://www.mtggoldfish.com/deck/7695687"
      },
      {
        "player": "sioutis_kk",
        "deck": "Affinity",
        "place": 5,
        "deck_url": "https://www.mtggoldfish.com/deck/7695693"
      },
      {
        "player": "WeareVenom",
        "deck": "Amulet Titan",
        "place": 6,
        "deck_url": "https://www.mtggoldfish.com/deck/7695680"
      },
      {
        "player": "azax",
        "deck": "Ruby Storm",
        "place": 7,
        "deck_url": "https://www.mtggoldfish.com/deck/7695674"
      },
      {
        "player": "JMAK2000",
        "deck": "Mono-Green Tron",
        "place": 8,
        "deck_url": "https://www.mtggoldfish.com/deck/7695671"
      },
      {
        "player": "scipios",
        "deck": "Jeskai Control",
        "place": 9,
        "deck_url": "https://www.mtggoldfish.com/deck/7695679"
      },
      {
        "player": "Ebnus",
        "deck": "Izzet Prowess",
        "place": 10,
        "deck_url": "https://www.mtggoldfish.com/deck/7695672"
      },
      {
        "player": "MTGHolic",
        "deck": "Jeskai Blink",
        "place": 11,
        "deck_url": "https://www.mtggoldfish.com/deck/7695686"
      },
      {
        "player": "klien7",
        "deck": "Jeskai Blink",
        "place": 12,
        "deck_url": "https://www.mtggoldfish.com/deck/7695682"
      },
      {
        "player": "Capitano_CL",
        "deck": "Ruby Storm",
        "place": 13,
        "deck_url": "https://www.mtggoldfish.com/deck/7695663"
      },
      {
        "player": "HugoVenda",
        "deck": "Jeskai Control",
        "place": 14,
        "deck_url": "https://www.mtggoldfish.com/deck/7695664"
      },
      {
        "player": "TomCairns",
        "deck": "Dimir Reanimator",
        "place": 15,
        "deck_url": "https://www.mtggoldfish.com/deck/7695691"
      },
      {
        "player": "Cachorrowo",
        "deck": "Ruby Storm",
        "place": 16,
        "deck_url": "https://www.mtggoldfish.com/deck/7695684"
      },
      {
        "player": "KadettiKersantti",
        "deck": "Grixis Reanimator",
        "place": 17,
        "deck_url": "https://www.mtggoldfish.com/deck/7695690"
      },
      {
        "player": "brandi96",
        "deck": "Boros Energy",
        "place": 18,
        "deck_url": "https://www.mtggoldfish.com/deck/7695670"
      },
      {
        "player": "Omegauo",
        "deck": "Esper GenericBlink",
        "place": 19,
        "deck_url": "https://www.mtggoldfish.com/deck/7695661"
      },
      {
        "player": "toondoslav",
        "deck": "Esper GenericBlink",
        "place": 20,
        "deck_url": "https://www.mtggoldfish.com/deck/7695669"
      },
      {
        "player": "GigaChadSigmaMale",
        "deck": "Goryo&#39;s Vengeance",
        "place": 21,
        "deck_url": "https://www.mtggoldfish.com/deck/7695688"
      },
      {
        "player": "pepeteam",
        "deck": "Dimir Midrange",
        "place": 22,
        "deck_url": "https://www.mtggoldfish.com/deck/7695675"
      },
      {
        "player": "Univerce",
        "deck": "Affinity",
        "place": 23,
        "deck_url": "https://www.mtggoldfish.com/deck/7695685"
      },
      {
        "player": "chengyiw",
        "deck": "Goryo&#39;s Vengeance",
        "place": 24,
        "deck_url": "https://www.mtggoldfish.com/deck/7695678"
      },
      {
        "player": "felider",
        "deck": "Jeskai Blink",
        "place": 25,
        "deck_url": "https://www.mtggoldfish.com/deck/7695677"
      },
      {
        "player": "FakeShaver",
        "deck": "Belcher",
        "place": 26,
        "deck_url": "https://www.mtggoldfish.com/deck/7695662"
      },
      {
        "player": "Athenani",
        "deck": "Boros Energy",
        "place": 27,
        "deck_url": "https://www.mtggoldfish.com/deck/7695689"
      },
      {
        "player": "JPA93",
        "deck": "Neobrand",
        "place": 28,
        "deck_url": "https://www.mtggoldfish.com/deck/7695667"
      },
      {
        "player": "Terminus0",
        "deck": "Esper GenericBlink",
        "place": 29,
        "deck_url": "https://www.mtggoldfish.com/deck/7695673"
      },
      {
        "player": "Gerschi",
        "deck": "Living End",
        "place": 30,
        "deck_url": "https://www.mtggoldfish.com/deck/7695665"
      },
      {
        "player": "Venom1",
        "deck": "Jeskai Blink",
        "place": 31,
        "deck_url": "https://www.mtggoldfish.com/deck/7695666"
      },
      {
        "player": "bless_von",
        "deck": "Boros Energy",
        "place": 32,
        "deck_url": "https://www.mtggoldfish.com/deck/7695676"
      }
    ]
  },
  {
    "date": "2026-03-22",
    "format": "modern",
    "event": "Modern Last Chance 2026-03-22 (1)",
    "url": "https://www.mtggoldfish.com/tournament/62588",
    "players": 32,
    "decklists": [
      {
        "player": "ETBJezus",
        "deck": "Dimir Midrange",
        "place": 1,
        "deck_url": "https://www.mtggoldfish.com/deck/7697826"
      },
      {
        "player": "xDingusKhan",
        "deck": "Ruby Storm",
        "place": 2,
        "deck_url": "https://www.mtggoldfish.com/deck/7697814"
      },
      {
        "player": "Laplasjan",
        "deck": "Jeskai Blink",
        "place": 3,
        "deck_url": "https://www.mtggoldfish.com/deck/7697809"
      },
      {
        "player": "Pmizz",
        "deck": "Jeskai Blink",
        "place": 4,
        "deck_url": "https://www.mtggoldfish.com/deck/7697811"
      },
      {
        "player": "eclipse4343",
        "deck": "Azorius Control",
        "place": 5,
        "deck_url": "https://www.mtggoldfish.com/deck/7697818"
      },
      {
        "player": "O_danielakos",
        "deck": "Temur Prowess",
        "place": 6,
        "deck_url": "https://www.mtggoldfish.com/deck/7697803"
      },
      {
        "player": "Crovax90",
        "deck": "Jeskai Blink",
        "place": 7,
        "deck_url": "https://www.mtggoldfish.com/deck/7697813"
      },
      {
        "player": "RUBAO_oDonoDoMundo",
        "deck": "Ruby Storm",
        "place": 8,
        "deck_url": "https://www.mtggoldfish.com/deck/7697827"
      },
      {
        "player": "Yarfangel",
        "deck": "Jeskai Blink",
        "place": 9,
        "deck_url": "https://www.mtggoldfish.com/deck/7697828"
      },
      {
        "player": "Moorehardcore",
        "deck": "Yawgmoth",
        "place": 10,
        "deck_url": "https://www.mtggoldfish.com/deck/7697825"
      },
      {
        "player": "Univerce",
        "deck": "Affinity",
        "place": 11,
        "deck_url": "https://www.mtggoldfish.com/deck/7697822"
      },
      {
        "player": "sioutis_kk",
        "deck": "Affinity",
        "place": 12,
        "deck_url": "https://www.mtggoldfish.com/deck/7697831"
      },
      {
        "player": "Xerk",
        "deck": "Yawgmoth",
        "place": 13,
        "deck_url": "https://www.mtggoldfish.com/deck/7697806"
      },
      {
        "player": "cigarettesaftershrek",
        "deck": "Affinity",
        "place": 14,
        "deck_url": "https://www.mtggoldfish.com/deck/7697824"
      },
      {
        "player": "sokos13",
        "deck": "Jeskai Blink",
        "place": 15,
        "deck_url": "https://www.mtggoldfish.com/deck/7697800"
      },
      {
        "player": "toondoslav",
        "deck": "Esper GenericBlink",
        "place": 16,
        "deck_url": "https://www.mtggoldfish.com/deck/7697810"
      },
      {
        "player": "Nilsfit",
        "deck": "Jeskai Control",
        "place": 17,
        "deck_url": "https://www.mtggoldfish.com/deck/7697815"
      },
      {
        "player": "Napoleon_I",
        "deck": "Naya Energy",
        "place": 18,
        "deck_url": "https://www.mtggoldfish.com/deck/7697819"
      },
      {
        "player": "Cazuza",
        "deck": "Jeskai Blink",
        "place": 19,
        "deck_url": "https://www.mtggoldfish.com/deck/7697820"
      },
      {
        "player": "mendyourheart",
        "deck": "Domain Zoo",
        "place": 20,
        "deck_url": "https://www.mtggoldfish.com/deck/7697829"
      },
      {
        "player": "DemonicTutors",
        "deck": "Yawgmoth",
        "place": 21,
        "deck_url": "https://www.mtggoldfish.com/deck/7697821"
      },
      {
        "player": "Foxantes",
        "deck": "Boros Energy",
        "place": 22,
        "deck_url": "https://www.mtggoldfish.com/deck/7697812"
      },
      {
        "player": "Venom1",
        "deck": "Jeskai Blink",
        "place": 23,
        "deck_url": "https://www.mtggoldfish.com/deck/7697807"
      },
      {
        "player": "pottinkx",
        "deck": "Boros Energy",
        "place": 24,
        "deck_url": "https://www.mtggoldfish.com/deck/7697830"
      },
      {
        "player": "applefox",
        "deck": "Living End",
        "place": 25,
        "deck_url": "https://www.mtggoldfish.com/deck/7697823"
      },
      {
        "player": "MultiformatSuperstar",
        "deck": "Neobrand",
        "place": 26,
        "deck_url": "https://www.mtggoldfish.com/deck/7697817"
      },
      {
        "player": "J4K3ST3R02",
        "deck": "Affinity",
        "place": 27,
        "deck_url": "https://www.mtggoldfish.com/deck/7697808"
      },
      {
        "player": "LucasG1ggs",
        "deck": "Boros Energy",
        "place": 28,
        "deck_url": "https://www.mtggoldfish.com/deck/7697802"
      },
      {
        "player": "Xenowan",
        "deck": "Neobrand",
        "place": 29,
        "deck_url": "https://www.mtggoldfish.com/deck/7697816"
      },
      {
        "player": "aspiringspike",
        "deck": "Dimir Midrange",
        "place": 30,
        "deck_url": "https://www.mtggoldfish.com/deck/7697804"
      },
      {
        "player": "tibalt_of_red_sub",
        "deck": "Dimir Mill",
        "place": 31,
        "deck_url": "https://www.mtggoldfish.com/deck/7697805"
      },
      {
        "player": "Misplacedginger",
        "deck": "Jeskai Blink",
        "place": 32,
        "deck_url": "https://www.mtggoldfish.com/deck/7697801"
      }
    ]
  }
];
