#!/usr/bin/env python3
"""
Scrape MTGO LCQ results from Daybreak/WOTC published decklists.

MTGO publishes event results at:
  https://www.mtgo.com/decklist/{event-slug}

This script fetches the main listing page, finds LCQ events for Vintage
and Legacy, and writes data.js with structured results.

Usage:
  python scrape.py           # scrape and write data.js
  python scrape.py --dry-run # print what would be written
"""

import json
import re
import sys
from datetime import datetime, timedelta
from urllib.request import urlopen, Request
from urllib.error import URLError

MTGO_BASE = "https://www.mtgo.com"
LISTING_URL = f"{MTGO_BASE}/decklists"

# How far back to look (days)
LOOKBACK_DAYS = 180

HEADERS = {"User-Agent": "MTGO-LCQ-Dashboard/1.0"}


def fetch(url: str) -> str:
    req = Request(url, headers=HEADERS)
    with urlopen(req, timeout=30) as resp:
        return resp.read().decode("utf-8")


def parse_events_from_listing(html: str) -> list[dict]:
    """
    Parse the MTGO decklists listing page for LCQ events.
    Looks for links matching patterns like:
      /decklist/vintage-last-chance-qualifier-2026-03-22
      /decklist/legacy-lcq-2026-03-15
    """
    events = []
    cutoff = datetime.now() - timedelta(days=LOOKBACK_DAYS)

    # Match LCQ-related event links
    pattern = re.compile(
        r'href="(/decklist/('
        r'(?:vintage|legacy)[^"]*(?:lcq|last.chance)[^"]*'
        r'|(?:lcq|last.chance)[^"]*(?:vintage|legacy)[^"]*'
        r'))"',
        re.IGNORECASE,
    )

    for match in pattern.finditer(html):
        path = match.group(1)
        slug = match.group(2).lower()

        # Determine format
        if "vintage" in slug:
            fmt = "vintage"
        elif "legacy" in slug:
            fmt = "legacy"
        else:
            continue

        # Try to extract date from slug
        date_match = re.search(r"(\d{4})-(\d{2})-(\d{2})", slug)
        if date_match:
            event_date = datetime(
                int(date_match.group(1)),
                int(date_match.group(2)),
                int(date_match.group(3)),
            )
            if event_date < cutoff:
                continue
        else:
            event_date = None

        events.append({
            "path": path,
            "slug": slug,
            "format": fmt,
            "date": event_date.strftime("%Y-%m-%d") if event_date else None,
        })

    return events


def parse_event_detail(html: str, event: dict) -> dict | None:
    """
    Parse an individual event page to extract winner, deck name, and player count.
    MTGO event pages typically show a ranked list of players with decklists.
    The first entry is the winner.
    """
    # Try to find player count
    players_match = re.search(r"(\d+)\s*(?:players?|entries|participants)", html, re.I)
    player_count = int(players_match.group(1)) if players_match else 0

    # Try to find the first-place player and deck
    # Common pattern: the first decklist header contains the winner
    winner_match = re.search(
        r'class="[^"]*(?:winner|first|1st|champion)[^"]*"[^>]*>([^<]+)',
        html, re.I,
    )
    if not winner_match:
        # Fallback: first decklist entry
        winner_match = re.search(
            r'class="[^"]*decklist-header[^"]*"[^>]*>\s*(?:<[^>]+>)*\s*([A-Za-z0-9_]+)',
            html, re.I,
        )

    if not winner_match:
        return None

    winner = winner_match.group(1).strip()

    # Try to find deck name
    deck_match = re.search(
        r'class="[^"]*deck-?name[^"]*"[^>]*>([^<]+)',
        html, re.I,
    )
    deck = deck_match.group(1).strip() if deck_match else "Unknown"

    # Build event name from slug
    slug_clean = event["slug"].replace("-", " ").title()
    # Shorten common patterns
    slug_clean = slug_clean.replace("Last Chance Qualifier", "LCQ")

    return {
        "date": event["date"],
        "format": event["format"],
        "event": slug_clean,
        "players": player_count,
        "winner": winner,
        "deck": deck,
    }


def write_data_js(events: list[dict], path: str = "data.js"):
    """Write the data.js file that the dashboard consumes."""
    # Sort by date descending
    events.sort(key=lambda e: e.get("date", ""), reverse=True)

    lines = [
        "// Auto-generated by scrape.py — do not edit manually",
        f"// Last updated: {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}",
        "const LCQ_DATA = " + json.dumps(events, indent=2) + ";",
    ]

    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Wrote {len(events)} events to {path}")


def main():
    dry_run = "--dry-run" in sys.argv

    print(f"Fetching event listing from {LISTING_URL}...")
    try:
        listing_html = fetch(LISTING_URL)
    except URLError as e:
        print(f"Could not fetch listing: {e}")
        print("If running locally, ensure you have internet access.")
        print("Keeping existing data.js unchanged.")
        return

    events_meta = parse_events_from_listing(listing_html)
    print(f"Found {len(events_meta)} LCQ event links")

    if not events_meta:
        print("No LCQ events found on listing page.")
        print("The MTGO site structure may have changed — check scrape.py patterns.")
        return

    results = []
    for meta in events_meta:
        url = MTGO_BASE + meta["path"]
        print(f"  Fetching {url}...")
        try:
            detail_html = fetch(url)
            result = parse_event_detail(detail_html, meta)
            if result:
                results.append(result)
            else:
                print(f"    Could not parse winner from {meta['slug']}")
        except URLError as e:
            print(f"    Error fetching {url}: {e}")

    if dry_run:
        print("\n--- DRY RUN ---")
        print(json.dumps(results, indent=2))
    else:
        # Merge with existing data to avoid losing manually-added entries
        try:
            with open("data.js") as f:
                existing_text = f.read()
            # Extract JSON array from existing data.js
            match = re.search(r"const LCQ_DATA = (\[.*?\]);", existing_text, re.DOTALL)
            if match:
                existing = json.loads(match.group(1))
                # Deduplicate by (date, format, event)
                existing_keys = {
                    (e["date"], e["format"], e.get("event", "")) for e in results
                }
                for old in existing:
                    key = (old["date"], old["format"], old.get("event", ""))
                    if key not in existing_keys:
                        results.append(old)
        except (FileNotFoundError, json.JSONDecodeError):
            pass

        write_data_js(results)


if __name__ == "__main__":
    main()
