#!/usr/bin/env python3
"""
Scrape MTGO Last Chance event results from MTGGoldfish and write data.js.

MTGGoldfish indexes MTGO events with pre-classified deck archetypes,
which is more reliable than classifying from raw card lists.

Usage:
  python scrape.py           # scrape and write data.js
  python scrape.py --dry-run # print what would be written
"""

import json
import re
import sys
from datetime import datetime
from urllib.request import urlopen, Request
from urllib.error import URLError
from urllib.parse import quote

GOLDFISH_BASE = "https://www.mtggoldfish.com"
HEADERS = {"User-Agent": "Mozilla/5.0 (compatible; MTGO-LCQ-Dashboard/1.0)"}

FORMATS = {"vintage", "legacy", "modern", "standard"}

# Date range: March 2026
DATE_START = "03/01/2026"
DATE_END = "03/31/2026"


def fetch(url: str, retries: int = 2) -> str:
    req = Request(url, headers=HEADERS)
    for attempt in range(retries + 1):
        try:
            with urlopen(req, timeout=60) as resp:
                return resp.read().decode("utf-8")
        except (URLError, TimeoutError):
            if attempt < retries:
                import time
                time.sleep(2)
                continue
            raise


def search_events() -> list[dict]:
    """Search MTGGoldfish for Last Chance events in March 2026."""
    date_range = quote(f"{DATE_START} - {DATE_END}")

    search_url = (
        f"{GOLDFISH_BASE}/tournament_searches/create?"
        f"utf8=%E2%9C%93"
        f"&tournament_search%5Bname%5D=last+chance"
        f"&tournament_search%5Bformat%5D="
        f"&tournament_search%5Bdate_range%5D={date_range}"
        f"&commit=Search"
    )

    print(f"Searching MTGGoldfish for Last Chance events (March 2026)...")
    html = fetch(search_url)

    events = []
    row_pattern = re.compile(
        r"<tr>\s*"
        r"<td>(\d{4}-\d{2}-\d{2})</td>\s*"
        r"<td>\s*<a href=\"(/tournament/(\d+))\">([^<]+)</a>\s*</td>\s*"
        r"<td>(Vintage|Legacy|Modern|Standard|Pioneer)</td>\s*"
        r"<td>(\d+)</td>\s*"
        r"</tr>",
        re.IGNORECASE | re.DOTALL,
    )

    for m in row_pattern.finditer(html):
        date_str = m.group(1)
        path = m.group(2)
        tid = m.group(3)
        name = m.group(4).strip()
        fmt = m.group(5).lower()
        count = int(m.group(6))

        if fmt not in FORMATS:
            continue

        events.append({
            "date": date_str,
            "name": name,
            "format": fmt,
            "url": GOLDFISH_BASE + path,
            "tournament_id": tid,
            "decklist_count": count,
        })

    return events


def parse_tournament(html: str, event: dict) -> dict:
    """
    Parse a MTGGoldfish tournament page.
    Extracts all decklists with placement, archetype, player name, and deck URL.
    """
    decklists = []

    # Capture deck ID in the href so we can link directly to each decklist
    entry_pattern = re.compile(
        r"<tr\s+class='tournament-decklist-(?:odd|event)'>\s*"
        r"<td[^>]*>\s*(\d+)(?:st|nd|rd|th)\s*</td>\s*"
        r"<td>\s*<a href=\"/deck/(\d+)\">([^<]+)</a>.*?</td>\s*"
        r"<td>\s*<a href=\"/player/[^\"]+\">([^<]+)</a>\s*</td>",
        re.DOTALL,
    )

    for m in entry_pattern.finditer(html):
        place = int(m.group(1))
        deck_id = m.group(2)
        deck = m.group(3).strip()
        player = m.group(4).strip()
        decklists.append({
            "player": player,
            "deck": deck,
            "place": place,
            "deck_url": f"{GOLDFISH_BASE}/deck/{deck_id}",
        })

    return {
        "date": event["date"],
        "format": event["format"],
        "event": event["name"],
        "url": event["url"],
        "players": len(decklists) or event["decklist_count"],
        "decklists": decklists,
    }


def write_data_js(events: list[dict], path: str = "data.js"):
    events.sort(key=lambda e: e.get("date", ""), reverse=True)

    lines = [
        "// Auto-generated by scrape.py — do not edit manually",
        f"// Last updated: {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}",
        "const LCQ_DATA = " + json.dumps(events, indent=2) + ";",
    ]

    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Wrote {len(events)} events to {path}")


def main():
    dry_run = "--dry-run" in sys.argv

    try:
        events_meta = search_events()
    except URLError as e:
        print(f"Could not search MTGGoldfish: {e}")
        print("Keeping existing data.js unchanged.")
        return

    print(f"Found {len(events_meta)} Last Chance events")

    if not events_meta:
        print("No Last Chance events found.")
        return

    results = []
    for meta in events_meta:
        print(f"  Fetching {meta['url']}...")
        try:
            html = fetch(meta["url"])
            result = parse_tournament(html, meta)
            results.append(result)
            n = len(result["decklists"])
            winner = result["decklists"][0] if result["decklists"] else None
            if winner:
                print(f"    {n} decks — Winner: {winner['player']} ({winner['deck']})")
            else:
                print(f"    {n} decks (no entries parsed)")
        except URLError as e:
            print(f"    Error: {e}")

    # Deduplicate events that share the same player list
    # MTGGoldfish sometimes indexes the same event twice with different IDs
    deduped = []
    seen_fingerprints = set()
    for ev in results:
        players = tuple(d["player"] for d in ev["decklists"])
        fingerprint = (ev["date"], ev["format"], players)
        if fingerprint in seen_fingerprints:
            print(f"  Skipping duplicate: {ev['event']}")
            continue
        seen_fingerprints.add(fingerprint)
        deduped.append(ev)
    results = deduped

    if dry_run:
        print("\n--- DRY RUN ---")
        print(json.dumps(results, indent=2))
        return

    write_data_js(results)


if __name__ == "__main__":
    main()
